# Project Team Members

| Prepared by | Email | Prepared for |
| :-: | :-: | :-: |
| **_Hardani Ismu Nabil_** | _hardani.ismu.n@gmail.com_ | **_ND Stadium Collaborative Project 2025/2026_** |

# Notebook Target Definition

* **GOAL** create merged app metric dataframes by merge_asof left=df_metric from QualiPoc with right=df_sigcap
* **REQUIRED** to run Ardan-2026_analysis_* notebooks
* **DATE** This is for Gameday November 11th 2026 data

# ===============================
# ===============================

# A-Setup

### A-1: Housechores

In [1]:
import os
import pathlib

import numpy as np
import pandas as pd

In [2]:
PROJECT_ROOT = pathlib.Path('.').cwd().parent # you can also do it manually, for example ~/repos/NdSta2026


print('='*50, '[DATA DIRECTORY]')
DATA_DIR = PROJECT_ROOT / "data_raw"

print(f"Project Root: {PROJECT_ROOT}")
print(f"Looking for data in: {DATA_DIR}")



print('- '*25)
print('='*50, '[OUTPUT DIRECTORY]')

# OUTPUT_DIR = PROJECT_ROOT / 'output/output_July1st_sigcapDataProcessing/sigcap-merge_gameday5' # CHANGE this into the notebook file name
OUTPUT_DIR = PROJECT_ROOT / 'data_processed'
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Project Root: {PROJECT_ROOT}")
print(f"All outputs will be in: {OUTPUT_DIR}")

================================================== [DATA DIRECTORY]
Project Root: /home/analisis/repos/NDKI_01_ForGithub_ForArtifact_wintech_2026_stadium_paper_analysis
Looking for data in: /home/analisis/repos/NDKI_01_ForGithub_ForArtifact_wintech_2026_stadium_paper_analysis/data_raw
- - - - - - - - - - - - - - - - - - - - - - - - -
================================================== [OUTPUT DIRECTORY]
Project Root: /home/analisis/repos/NDKI_01_ForGithub_ForArtifact_wintech_2026_stadium_paper_analysis
All outputs will be in: /home/analisis/repos/NDKI_01_ForGithub_ForArtifact_wintech_2026_stadium_paper_analysis/data_processed

### A-2: SigCap data for correlation

In [3]:
selected_cols = ['timestamp', 'latitude', 'longitude', 'uuid', 'operator', 'Location', 'network_type*', 'wifi_connected_primary_freq_mhz']    

df_bow = pd.read_csv(DATA_DIR /'game5_sigcap_csv/20251108_sigcap_bowl_general.csv').assign(Location='Bowl')
df_bow['timestamp'] = pd.to_datetime(df_bow['timestamp'])

df_con = pd.read_csv(DATA_DIR / 'game5_sigcap_csv/20251108_sigcap_concourse_general.csv').assign(Location='Concourse')
df_con['timestamp'] = pd.to_datetime(df_con['timestamp'])
df_con = df_con[df_con['timestamp'] < '2025-11-09 00:00:00']

df_bowcon = pd.read_csv(DATA_DIR / 'game5_sigcap_csv/20251108_sigcap_bowcon_general.csv')
df_bowcon['timestamp'] = pd.to_datetime(df_bowcon['timestamp'])
df_bowcon_bow = df_bowcon[df_bowcon['timestamp'] < '2025-11-08 21:38:42'].assign(Location='Bowl')
df_bowcon_con = df_bowcon[df_bowcon['timestamp'] >= '2025-11-08 21:38:42'].assign(Location='Concourse')

df_sigcap = pd.concat([df_bow, df_con, df_bowcon_bow, df_bowcon_con]).reset_index(drop=True)
df_sigcap = df_sigcap[selected_cols].sort_values('timestamp')
df_sigcap['uuid'] = df_sigcap['uuid'].str.slice(0, 8)
df_sigcap.to_csv(OUTPUT_DIR / '20251108_sigcap_general.csv', index=False)
df_sigcap.to_csv(DATA_DIR / 'game5_sigcap_csv/20251108_sigcap_general.csv', index=False)
print(f"Sigcap data shape: {df_sigcap.shape}")
display(df_sigcap[['uuid', 'operator']].drop_duplicates())
df_sigcap.head()

/tmp/ipykernel_29154/2079936554.py:3: DtypeWarning: Columns (0: override_network_type, 1: wifi_2.4_other6_ssid, 2: wifi_2.4_other6_bssid, 3: wifi_2.4_other6_standard, 4: wifi_2.4_other7_ssid, 5: wifi_2.4_other7_bssid, 6: wifi_2.4_other7_standard, 7: wifi_2.4_other8_ssid, 8: wifi_2.4_other8_bssid, 9: wifi_2.4_other8_standard, 10: wifi_5_other120_ssid, 11: wifi_5_other120_bssid, 12: wifi_5_other120_standard, 13: wifi_5_other121_ssid, 14: wifi_5_other121_bssid, 15: wifi_5_other121_standard, 16: wifi_5_other122_ssid, 17: wifi_5_other122_bssid, 18: wifi_5_other122_standard, 19: wifi_5_other123_ssid, 20: wifi_5_other123_bssid, 21: wifi_5_other123_standard, 22: wifi_5_other124_ssid, 23: wifi_5_other124_bssid, 24: wifi_5_other124_standard, 25: wifi_5_other125_ssid, 26: wifi_5_other125_bssid, 27: wifi_5_other125_standard, 28: wifi_5_other126_ssid, 29: wifi_5_other126_bssid, 30: wifi_5_other126_standard, 31: wifi_5_other127_ssid, 32: wifi_5_other127_bssid, 33: wifi_5_other127_standard, 34: wifi_5_other128_ssid, 35: wifi_5_other128_bssid, 36: wifi_5_other128_standard, 37: wifi_5_other129_ssid, 38: wifi_5_other129_bssid, 39: wifi_5_other129_standard, 40: wifi_5_other130_ssid, 41: wifi_5_other130_bssid, 42: wifi_5_other130_standard, 43: wifi_5_other131_ssid, 44: wifi_5_other131_bssid, 45: wifi_5_other131_standard, 46: wifi_5_other132_ssid, 47: wifi_5_other132_bssid, 48: wifi_5_other132_standard, 49: wifi_5_other133_ssid, 50: wifi_5_other133_bssid, 51: wifi_5_other133_standard, 52: wifi_5_other134_ssid, 53: wifi_5_other134_bssid, 54: wifi_5_other134_standard, 55: wifi_6_other41_ssid, 56: wifi_6_other41_bssid, 57: wifi_6_other41_standard, 58: wifi_6_other42_ssid, 59: wifi_6_other42_bssid, 60: wifi_6_other42_standard, 61: wifi_6_other43_ssid, 62: wifi_6_other43_bssid, 63: wifi_6_other43_standard, 64: wifi_6_other44_ssid, 65: wifi_6_other44_bssid, 66: wifi_6_other44_standard, 67: wifi_6_other45_ssid, 68: wifi_6_other45_bssid, 69: wifi_6_other45_standard, 70: wifi_6_other46_ssid, 71: wifi_6_other46_bssid, 72: wifi_6_other46_standard, 73: wifi_6_other47_ssid, 74: wifi_6_other47_bssid, 75: wifi_6_other47_standard, 76: wifi_6_other48_ssid, 77: wifi_6_other48_bssid, 78: wifi_6_other48_standard, 79: wifi_6_other49_ssid, 80: wifi_6_other49_bssid, 81: wifi_6_other49_standard, 82: wifi_6_other50_ssid, 83: wifi_6_other50_bssid, 84: wifi_6_other50_standard, 85: wifi_6_other51_ssid, 86: wifi_6_other51_bssid, 87: wifi_6_other51_standard, 88: wifi_6_other52_ssid, 89: wifi_6_other52_bssid, 90: wifi_6_other52_standard, 91: wifi_6_other53_ssid, 92: wifi_6_other53_bssid, 93: wifi_6_other53_standard, 94: wifi_6_other54_ssid, 95: wifi_6_other54_bssid, 96: wifi_6_other54_standard, 97: wifi_6_other55_ssid, 98: wifi_6_other55_bssid, 99: wifi_6_other55_standard, 100: wifi_6_other56_ssid, 101: wifi_6_other56_bssid, 102: wifi_6_other56_standard, 103: wifi_6_other57_ssid, 104: wifi_6_other57_bssid, 105: wifi_6_other57_standard, 106: wifi_6_other58_ssid, 107: wifi_6_other58_bssid, 108: wifi_6_other58_standard, 109: wifi_6_other59_ssid, 110: wifi_6_other59_bssid, 111: wifi_6_other59_standard) have mixed types. Specify dtype option on import or set low_memory=False.
  df_bow = pd.read_csv(DATA_DIR /'game5_sigcap_csv/20251108_sigcap_bowl_general.csv').assign(Location='Bowl')
/tmp/ipykernel_29154/2079936554.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_bow = pd.read_csv(DATA_DIR /'game5_sigcap_csv/20251108_sigcap_bowl_general.csv').assign(Location='Bowl')

/tmp/ipykernel_29154/2079936554.py:6: DtypeWarning: Columns (0: wifi_2.4_other5_ssid, 1: wifi_2.4_other5_bssid, 2: wifi_2.4_other5_standard, 3: wifi_2.4_other6_ssid, 4: wifi_2.4_other6_bssid, 5: wifi_2.4_other6_standard, 6: wifi_2.4_other7_ssid, 7: wifi_2.4_other7_bssid, 8: wifi_2.4_other7_standard, 9: wifi_2.4_other8_ssid, 10: wifi_2.4_other8_bssid, 11: wifi_2.4_other8_standard, 12: wifi_2.4_other9_ssid, 13: wifi_2.4_other9_bssid, 14: wifi_2.4_other9_standard, 15: wifi_2.4_other10_ssid, 16: wifi_2.4_other10_bssid, 17: wifi_2.4_other10_standard, 18: wifi_2.4_other11_ssid, 19: wifi_2.4_other11_bssid, 20: wifi_2.4_other11_standard, 21: wifi_2.4_other12_ssid, 22: wifi_2.4_other12_bssid, 23: wifi_2.4_other12_standard, 24: wifi_2.4_other13_ssid, 25: wifi_2.4_other13_bssid, 26: wifi_2.4_other13_standard, 27: wifi_2.4_other14_ssid, 28: wifi_2.4_other14_bssid, 29: wifi_2.4_other14_standard, 30: wifi_2.4_other15_ssid, 31: wifi_2.4_other15_bssid, 32: wifi_2.4_other15_standard, 33: wifi_2.4_other16_ssid, 34: wifi_2.4_other16_bssid, 35: wifi_2.4_other16_standard, 36: wifi_2.4_other17_ssid, 37: wifi_2.4_other17_bssid, 38: wifi_2.4_other17_standard, 39: wifi_2.4_other18_ssid, 40: wifi_2.4_other18_bssid, 41: wifi_2.4_other18_standard, 42: wifi_2.4_other19_ssid, 43: wifi_2.4_other19_bssid, 44: wifi_2.4_other19_standard, 45: wifi_2.4_other20_ssid, 46: wifi_2.4_other20_bssid, 47: wifi_2.4_other20_standard, 48: wifi_2.4_other21_ssid, 49: wifi_2.4_other21_bssid, 50: wifi_2.4_other21_standard, 51: wifi_2.4_other22_ssid, 52: wifi_2.4_other22_bssid, 53: wifi_2.4_other22_standard, 54: wifi_2.4_other23_ssid, 55: wifi_2.4_other23_bssid, 56: wifi_2.4_other23_standard, 57: wifi_2.4_other24_ssid, 58: wifi_2.4_other24_bssid, 59: wifi_2.4_other24_standard, 60: wifi_2.4_other25_ssid, 61: wifi_2.4_other25_bssid, 62: wifi_2.4_other25_standard, 63: wifi_2.4_other26_ssid, 64: wifi_2.4_other26_bssid, 65: wifi_2.4_other26_standard, 66: wifi_5_other74_ssid, 67: wifi_5_other74_bssid, 68: wifi_5_other74_standard, 69: wifi_5_other75_ssid, 70: wifi_5_other75_bssid, 71: wifi_5_other75_standard, 72: wifi_5_other76_ssid, 73: wifi_5_other76_bssid, 74: wifi_5_other76_standard, 75: wifi_5_other77_ssid, 76: wifi_5_other77_bssid, 77: wifi_5_other77_standard, 78: wifi_5_other78_ssid, 79: wifi_5_other78_bssid, 80: wifi_5_other78_standard, 81: wifi_5_other79_ssid, 82: wifi_5_other79_bssid, 83: wifi_5_other79_standard, 84: wifi_5_other80_ssid, 85: wifi_5_other80_bssid, 86: wifi_5_other80_standard, 87: wifi_6_other20_ssid, 88: wifi_6_other20_bssid, 89: wifi_6_other20_standard, 90: wifi_6_other21_ssid, 91: wifi_6_other21_bssid, 92: wifi_6_other21_standard, 93: wifi_6_other22_ssid, 94: wifi_6_other22_bssid, 95: wifi_6_other22_standard, 96: wifi_6_other23_ssid, 97: wifi_6_other23_bssid, 98: wifi_6_other23_standard, 99: wifi_6_other24_ssid, 100: wifi_6_other24_bssid, 101: wifi_6_other24_standard) have mixed types. Specify dtype option on import or set low_memory=False.
  df_con = pd.read_csv(DATA_DIR / 'game5_sigcap_csv/20251108_sigcap_concourse_general.csv').assign(Location='Concourse')
/tmp/ipykernel_29154/2079936554.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_con = pd.read_csv(DATA_DIR / 'game5_sigcap_csv/20251108_sigcap_concourse_general.csv').assign(Location='Concourse')

/tmp/ipykernel_29154/2079936554.py:10: DtypeWarning: Columns (0: wifi_2.4_other3_ssid, 1: wifi_2.4_other3_bssid, 2: wifi_2.4_other3_standard, 3: wifi_2.4_other4_ssid, 4: wifi_2.4_other4_bssid, 5: wifi_2.4_other4_standard, 6: wifi_2.4_other5_ssid, 7: wifi_2.4_other5_bssid, 8: wifi_2.4_other5_standard, 9: wifi_2.4_other6_ssid, 10: wifi_2.4_other6_bssid, 11: wifi_2.4_other6_standard, 12: wifi_2.4_other7_ssid, 13: wifi_2.4_other7_bssid, 14: wifi_2.4_other7_standard, 15: wifi_5_other59_ssid, 16: wifi_5_other59_bssid, 17: wifi_5_other59_standard, 18: wifi_5_other60_ssid, 19: wifi_5_other60_bssid, 20: wifi_5_other60_standard, 21: wifi_5_other61_ssid, 22: wifi_5_other61_bssid, 23: wifi_5_other61_standard, 24: wifi_5_other62_ssid, 25: wifi_5_other62_bssid, 26: wifi_5_other62_standard, 27: wifi_5_other63_ssid, 28: wifi_5_other63_bssid, 29: wifi_5_other63_standard, 30: wifi_5_other64_ssid, 31: wifi_5_other64_bssid, 32: wifi_5_other64_standard, 33: wifi_5_other65_ssid, 34: wifi_5_other65_bssid, 35: wifi_5_other65_standard, 36: wifi_5_other66_ssid, 37: wifi_5_other66_bssid, 38: wifi_5_other66_standard, 39: wifi_5_other67_ssid, 40: wifi_5_other67_bssid, 41: wifi_5_other67_standard, 42: wifi_5_other68_ssid, 43: wifi_5_other68_bssid, 44: wifi_5_other68_standard, 45: wifi_5_other69_ssid, 46: wifi_5_other69_bssid, 47: wifi_5_other69_standard, 48: wifi_5_other70_ssid, 49: wifi_5_other70_bssid, 50: wifi_5_other70_standard, 51: wifi_5_other71_ssid, 52: wifi_5_other71_bssid, 53: wifi_5_other71_standard, 54: wifi_5_other72_ssid, 55: wifi_5_other72_bssid, 56: wifi_5_other72_standard, 57: wifi_5_other73_ssid, 58: wifi_5_other73_bssid, 59: wifi_5_other73_standard, 60: wifi_5_other74_ssid, 61: wifi_5_other74_bssid, 62: wifi_5_other74_standard, 63: wifi_5_other75_ssid, 64: wifi_5_other75_bssid, 65: wifi_5_other75_standard, 66: wifi_5_other76_ssid, 67: wifi_5_other76_bssid, 68: wifi_5_other76_standard, 69: wifi_5_other77_ssid, 70: wifi_5_other77_bssid, 71: wifi_5_other77_standard, 72: wifi_5_other78_ssid, 73: wifi_5_other78_bssid, 74: wifi_5_other78_standard, 75: wifi_5_other79_ssid, 76: wifi_5_other79_bssid, 77: wifi_5_other79_standard, 78: wifi_5_other80_ssid, 79: wifi_5_other80_bssid, 80: wifi_5_other80_standard, 81: wifi_5_other81_ssid, 82: wifi_5_other81_bssid, 83: wifi_5_other81_standard, 84: wifi_5_other82_ssid, 85: wifi_5_other82_bssid, 86: wifi_5_other82_standard, 87: wifi_5_other83_ssid, 88: wifi_5_other83_bssid, 89: wifi_5_other83_standard, 90: wifi_5_other84_ssid, 91: wifi_5_other84_bssid, 92: wifi_5_other84_standard, 93: wifi_5_other85_ssid, 94: wifi_5_other85_bssid, 95: wifi_5_other85_standard, 96: wifi_5_other86_ssid, 97: wifi_5_other86_bssid, 98: wifi_5_other86_standard, 99: wifi_5_other87_ssid, 100: wifi_5_other87_bssid, 101: wifi_5_other87_standard, 102: wifi_5_other88_ssid, 103: wifi_5_other88_bssid, 104: wifi_5_other88_standard, 105: wifi_5_other89_ssid, 106: wifi_5_other89_bssid, 107: wifi_5_other89_standard, 108: wifi_5_other90_ssid, 109: wifi_5_other90_bssid, 110: wifi_5_other90_standard, 111: wifi_5_other91_ssid, 112: wifi_5_other91_bssid, 113: wifi_5_other91_standard, 114: wifi_5_other92_ssid, 115: wifi_5_other92_bssid, 116: wifi_5_other92_standard, 117: wifi_5_other93_ssid, 118: wifi_5_other93_bssid, 119: wifi_5_other93_standard, 120: wifi_5_other94_ssid, 121: wifi_5_other94_bssid, 122: wifi_5_other94_standard, 123: wifi_5_other95_ssid, 124: wifi_5_other95_bssid, 125: wifi_5_other95_standard, 126: wifi_5_other96_ssid, 127: wifi_5_other96_bssid, 128: wifi_5_other96_standard, 129: wifi_5_other97_ssid, 130: wifi_5_other97_bssid, 131: wifi_5_other97_standard, 132: wifi_5_other98_ssid, 133: wifi_5_other98_bssid, 134: wifi_5_other98_standard, 135: wifi_5_other99_ssid, 136: wifi_5_other99_bssid, 137: wifi_5_other99_standard, 138: wifi_5_other100_ssid, 139: wifi_5_other100_bssid, 140: wifi_5_other100_standard, 141: wifi_5_other101_ssid, 142: wifi_5_other101_bssid, 143: wifi_5_other101_standard, 144: wifi_5_other102_ssid, 145: wifi_5_other102_bssid, 146: wifi_5_other102_standard, 147: wifi_5_other103_ssid, 148: wifi_5_other103_bssid, 149: wifi_5_other103_standard, 150: wifi_5_other104_ssid, 151: wifi_5_other104_bssid, 152: wifi_5_other104_standard, 153: wifi_5_other105_ssid, 154: wifi_5_other105_bssid, 155: wifi_5_other105_standard, 156: wifi_5_other106_ssid, 157: wifi_5_other106_bssid, 158: wifi_5_other106_standard, 159: wifi_5_other107_ssid, 160: wifi_5_other107_bssid, 161: wifi_5_other107_standard, 162: wifi_5_other108_ssid, 163: wifi_5_other108_bssid, 164: wifi_5_other108_standard, 165: wifi_5_other109_ssid, 166: wifi_5_other109_bssid, 167: wifi_5_other109_standard, 168: wifi_5_other110_ssid, 169: wifi_5_other110_bssid, 170: wifi_5_other110_standard, 171: wifi_5_other111_ssid, 172: wifi_5_other111_bssid, 173: wifi_5_other111_standard, 174: wifi_5_other112_ssid, 175: wifi_5_other112_bssid, 176: wifi_5_other112_standard, 177: wifi_5_other113_ssid, 178: wifi_5_other113_bssid, 179: wifi_5_other113_standard, 180: wifi_5_other114_ssid, 181: wifi_5_other114_bssid, 182: wifi_5_other114_standard, 183: wifi_5_other115_ssid, 184: wifi_5_other115_bssid, 185: wifi_5_other115_standard, 186: wifi_5_other116_ssid, 187: wifi_5_other116_bssid, 188: wifi_5_other116_standard, 189: wifi_5_other117_ssid, 190: wifi_5_other117_bssid, 191: wifi_5_other117_standard, 192: wifi_5_other118_ssid, 193: wifi_5_other118_bssid, 194: wifi_5_other118_standard, 195: wifi_5_other119_ssid, 196: wifi_5_other119_bssid, 197: wifi_5_other119_standard, 198: wifi_5_other120_ssid, 199: wifi_5_other120_bssid, 200: wifi_5_other120_standard, 201: wifi_5_other121_ssid, 202: wifi_5_other121_bssid, 203: wifi_5_other121_standard, 204: wifi_5_other122_ssid, 205: wifi_5_other122_bssid, 206: wifi_5_other122_standard, 207: wifi_5_other123_ssid, 208: wifi_5_other123_bssid, 209: wifi_5_other123_standard, 210: wifi_6_other12_ssid, 211: wifi_6_other12_bssid, 212: wifi_6_other12_standard, 213: wifi_6_other13_ssid, 214: wifi_6_other13_bssid, 215: wifi_6_other13_standard, 216: wifi_6_other14_ssid, 217: wifi_6_other14_bssid, 218: wifi_6_other14_standard, 219: wifi_6_other15_ssid, 220: wifi_6_other15_bssid, 221: wifi_6_other15_standard, 222: wifi_6_other16_ssid, 223: wifi_6_other16_bssid, 224: wifi_6_other16_standard, 225: wifi_6_other17_ssid, 226: wifi_6_other17_bssid, 227: wifi_6_other17_standard, 228: wifi_6_other18_ssid, 229: wifi_6_other18_bssid, 230: wifi_6_other18_standard, 231: wifi_6_other19_ssid, 232: wifi_6_other19_bssid, 233: wifi_6_other19_standard, 234: wifi_6_other20_ssid, 235: wifi_6_other20_bssid, 236: wifi_6_other20_standard, 237: wifi_6_other21_ssid, 238: wifi_6_other21_bssid, 239: wifi_6_other21_standard, 240: wifi_6_other22_ssid, 241: wifi_6_other22_bssid, 242: wifi_6_other22_standard, 243: wifi_6_other23_ssid, 244: wifi_6_other23_bssid, 245: wifi_6_other23_standard, 246: wifi_6_other24_ssid, 247: wifi_6_other24_bssid, 248: wifi_6_other24_standard, 249: wifi_6_other25_ssid, 250: wifi_6_other25_bssid, 251: wifi_6_other25_standard, 252: wifi_6_other26_ssid, 253: wifi_6_other26_bssid, 254: wifi_6_other26_standard, 255: wifi_6_other27_ssid, 256: wifi_6_other27_bssid, 257: wifi_6_other27_standard, 258: wifi_6_other28_ssid, 259: wifi_6_other28_bssid, 260: wifi_6_other28_standard, 261: wifi_6_other29_ssid, 262: wifi_6_other29_bssid, 263: wifi_6_other29_standard, 264: wifi_6_other30_ssid, 265: wifi_6_other30_bssid, 266: wifi_6_other30_standard, 267: wifi_6_other31_ssid, 268: wifi_6_other31_bssid, 269: wifi_6_other31_standard, 270: wifi_6_other32_ssid, 271: wifi_6_other32_bssid, 272: wifi_6_other32_standard, 273: wifi_6_other33_ssid, 274: wifi_6_other33_bssid, 275: wifi_6_other33_standard, 276: wifi_6_other34_ssid, 277: wifi_6_other34_bssid, 278: wifi_6_other34_standard, 279: wifi_6_other35_ssid, 280: wifi_6_other35_bssid, 281: wifi_6_other35_standard, 282: wifi_6_other36_ssid, 283: wifi_6_other36_bssid, 284: wifi_6_other36_standard, 285: wifi_6_other37_ssid, 286: wifi_6_other37_bssid, 287: wifi_6_other37_standard, 288: wifi_6_other38_ssid, 289: wifi_6_other38_bssid, 290: wifi_6_other38_standard, 291: wifi_6_other39_ssid, 292: wifi_6_other39_bssid, 293: wifi_6_other39_standard, 294: wifi_6_other40_ssid, 295: wifi_6_other40_bssid, 296: wifi_6_other40_standard, 297: wifi_6_other41_ssid, 298: wifi_6_other41_bssid, 299: wifi_6_other41_standard, 300: wifi_6_other42_ssid, 301: wifi_6_other42_bssid, 302: wifi_6_other42_standard, 303: wifi_6_other43_ssid, 304: wifi_6_other43_bssid, 305: wifi_6_other43_standard, 306: wifi_6_other44_ssid, 307: wifi_6_other44_bssid, 308: wifi_6_other44_standard, 309: wifi_6_other45_ssid, 310: wifi_6_other45_bssid, 311: wifi_6_other45_standard, 312: wifi_6_other46_ssid, 313: wifi_6_other46_bssid, 314: wifi_6_other46_standard, 315: wifi_6_other47_ssid, 316: wifi_6_other47_bssid, 317: wifi_6_other47_standard, 318: wifi_6_other48_ssid, 319: wifi_6_other48_bssid, 320: wifi_6_other48_standard, 321: wifi_6_other49_ssid, 322: wifi_6_other49_bssid, 323: wifi_6_other49_standard, 324: wifi_6_other50_ssid, 325: wifi_6_other50_bssid, 326: wifi_6_other50_standard, 327: wifi_6_other51_ssid, 328: wifi_6_other51_bssid, 329: wifi_6_other51_standard, 330: wifi_6_other52_ssid, 331: wifi_6_other52_bssid, 332: wifi_6_other52_standard, 333: wifi_6_other53_ssid, 334: wifi_6_other53_bssid, 335: wifi_6_other53_standard, 336: wifi_6_other54_ssid, 337: wifi_6_other54_bssid, 338: wifi_6_other54_standard, 339: wifi_6_other55_ssid, 340: wifi_6_other55_bssid, 341: wifi_6_other55_standard, 342: wifi_6_other56_ssid, 343: wifi_6_other56_bssid, 344: wifi_6_other56_standard, 345: wifi_6_other57_ssid, 346: wifi_6_other57_bssid, 347: wifi_6_other57_standard, 348: wifi_6_other58_ssid, 349: wifi_6_other58_bssid, 350: wifi_6_other58_standard, 351: wifi_6_other59_ssid, 352: wifi_6_other59_bssid, 353: wifi_6_other59_standard, 354: wifi_6_other60_ssid, 355: wifi_6_other60_bssid, 356: wifi_6_other60_standard, 357: wifi_6_other61_ssid, 358: wifi_6_other61_bssid, 359: wifi_6_other61_standard, 360: wifi_6_other62_ssid, 361: wifi_6_other62_bssid, 362: wifi_6_other62_standard, 363: wifi_6_other63_ssid, 364: wifi_6_other63_bssid, 365: wifi_6_other63_standard, 366: wifi_6_other64_ssid, 367: wifi_6_other64_bssid, 368: wifi_6_other64_standard, 369: wifi_6_other65_ssid, 370: wifi_6_other65_bssid, 371: wifi_6_other65_standard, 372: wifi_6_other66_ssid, 373: wifi_6_other66_bssid, 374: wifi_6_other66_standard, 375: wifi_6_other67_ssid, 376: wifi_6_other67_bssid, 377: wifi_6_other67_standard, 378: wifi_6_other68_ssid, 379: wifi_6_other68_bssid, 380: wifi_6_other68_standard, 381: wifi_6_other69_ssid, 382: wifi_6_other69_bssid, 383: wifi_6_other69_standard, 384: wifi_6_other70_ssid, 385: wifi_6_other70_bssid, 386: wifi_6_other70_standard) have mixed types. Specify dtype option on import or set low_memory=False.
  df_bowcon = pd.read_csv(DATA_DIR / 'game5_sigcap_csv/20251108_sigcap_bowcon_general.csv')
/tmp/ipykernel_29154/2079936554.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_bowcon_bow = df_bowcon[df_bowcon['timestamp'] < '2025-11-08 21:38:42'].assign(Location='Bowl')

/tmp/ipykernel_29154/2079936554.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_bowcon_con = df_bowcon[df_bowcon['timestamp'] >= '2025-11-08 21:38:42'].assign(Location='Concourse')

Sigcap data shape: (2956, 8)

          uuid  operator
0     64957d65  T-Mobile
1809  a0654bd3      AT&T
74    7c36e7df   Verizon

,timestamp,latitude,longitude,uuid,operator,Location,network_type*,wifi_connected_primary_freq_mhz
0,2025-11-08 20:11:13.830000-05:00,41.698083,-86.233063,64957d65,T-Mobile,Bowl,NR,NaN
1,2025-11-08 20:11:18.827000-05:00,41.697940,-86.233196,64957d65,T-Mobile,Bowl,NR,NaN
2,2025-11-08 20:11:23.825000-05:00,41.697925,-86.233217,64957d65,T-Mobile,Bowl,NR,NaN
3,2025-11-08 20:11:28.821000-05:00,41.697918,-86.233223,64957d65,T-Mobile,Bowl,NR,NaN
4,2025-11-08 20:11:33.826000-05:00,41.697918,-86.233223,64957d65,T-Mobile,Bowl,NR,NaN

# ===============================
# ===============================

# B-Browsing analysis

### plc, data creation

In [4]:
df_browser = pd.concat([
    pd.read_csv(DATA_DIR / 'game5_qp_csv/20251108_Game_Bowl_Browser.csv').assign(Location='Bowl'),
    pd.read_csv(DATA_DIR / 'game5_qp_csv/20251108_Game_Concourse_Browser.csv').assign(Location='Concourse')
])

df_browser['Time'] = pd.to_datetime(df_browser['Time'])
df_browser = df_browser.sort_values('Time')
display(df_browser[['Unit', 'Operator']].value_counts())

# Taken from SigCap
uuid_map = {
    'QualiPoc_619529': '64957d65',	 #T-Mobile
    'QualiPoc_361786': 'a0654bd3',	 #AT&T
    'QualiPoc_396840': '7c36e7df'	 #Verizon
}

df_browser['uuid'] = df_browser['Unit'].map(uuid_map)

print(f"Browser data shape: {df_browser.shape}")
df_browser.head()

Unit             Operator
QualiPoc_396840  Verizon     324
QualiPoc_361786  AT&T        300
QualiPoc_619529  T-Mobile    192
QualiPoc_396840  T-Mobile      7
Name: count, dtype: int64

Browser data shape: (823, 34)

,Time,Latitude,Longitude,Unit,Operator,Data Technology Reporting,Browsing Duration,Download Duration,IP Throughput,Access Duration,...,Host,Protocol,Operation,AP Type,AP Profile Name,Test Name,Direction,Test Status,Location,uuid
0,2025-11-08 20:13:16.526,41.697948,-86.233408,QualiPoc_619529,T-Mobile,NaN,23.200,9.124,2146.291977,264.0,...,instagram.com,HTTP,GET,default supl mms xcap,T-Mobile US LTE,Browsing,Downlink,Completed,Bowl,64957d65
1,2025-11-08 20:13:31.012,41.697949,-86.233401,QualiPoc_619529,T-Mobile,NaN,13.194,8.210,1214.959318,2194.0,...,x.com,HTTP,GET,default supl mms xcap,T-Mobile US LTE,Browsing,Downlink,Completed,Bowl,64957d65
2,2025-11-08 20:13:56.509,41.697949,-86.233402,QualiPoc_619529,T-Mobile,NaN,24.312,13.908,964.000575,NaN,...,tiktok.com,HTTP,GET,default supl mms xcap,T-Mobile US LTE,Browsing,Downlink,Completed,Bowl,64957d65
3,2025-11-08 20:14:04.497,41.697950,-86.233402,QualiPoc_619529,T-Mobile,NaN,6.685,4.399,2274.640600,560.0,...,youtube.com,HTTP,GET,default supl mms xcap,T-Mobile US LTE,Browsing,Downlink,Completed,Bowl,64957d65
4,2025-11-08 20:14:08.448,41.697949,-86.233402,QualiPoc_619529,T-Mobile,NaN,2.673,1.969,4318.561706,341.0,...,facebook.com,HTTP,GET,default supl mms xcap,T-Mobile US LTE,Browsing,Downlink,Completed,Bowl,64957d65

In [5]:
print("Original shape:", df_browser.shape)

Original shape: (823, 34)

In [6]:
# 1. Identify columns
group_cols = [col for col in df_browser.columns if col != "Data Technology Reporting"]

# 2. Group with dropna=False
df_collapsed = (
    df_browser.fillna({"Data Technology Reporting": "NaN"})
    .groupby(group_cols, as_index=False, dropna=False)["Data Technology Reporting"]
    .agg(", ".join)
)

print("New shape:", df_collapsed.shape)
df_browser = df_collapsed.copy()

New shape: (773, 34)

In [7]:
df_browser[df_browser['Location'] == 'Bowl'].describe()

,Time,Latitude,Longitude,Browsing Duration,Download Duration,IP Throughput,Access Duration,Time To First Byte,Kbytes In First Second,Round Trip Time (RTT),Size Of Webpage,Number of Redirections,Number of Resources,Number of Resources not loaded,Number of Images,Primary DNS
count,413,413.000000,413.000000,363.000000,347.000000,3.470000e+02,382.000000,382.000000,382.000000,392.000000,363.000000,413.000000,413.000000,413.000000,413.000000,0.0
mean,2025-11-08 20:49:35.673820,41.698316,-86.234082,7.453634,2.264798,4.793060e+04,818.989529,1658.141361,777.164264,152.443878,2976.340716,1.460048,95.622276,0.184019,11.009685,NaN
min,2025-11-08 20:13:16.526000,41.697913,-86.234831,1.065000,0.019000,3.599756e+02,53.000000,74.000000,0.000000,0.000000,87.376000,0.000000,0.000000,0.000000,0.000000,NaN
25%,2025-11-08 20:31:00.075000,41.697936,-86.234514,2.799500,0.713000,4.201989e+03,278.500000,431.000000,299.290152,36.000000,1140.270500,1.000000,24.000000,0.000000,2.000000,NaN
50%,2025-11-08 20:46:00.759000,41.697953,-86.234484,4.480000,1.375000,1.215055e+04,381.500000,576.000000,596.496202,61.000000,2385.223000,1.000000,55.000000,0.000000,6.000000,NaN
75%,2025-11-08 21:03:59.448000,41.698834,-86.233402,8.309500,2.417000,4.007480e+04,581.750000,892.500000,1043.783443,106.000000,4692.022000,2.000000,114.000000,0.000000,13.000000,NaN
max,2025-11-08 21:37:36.168000,41.698910,-86.233369,84.879000,25.920000,1.090275e+06,18174.000000,36536.000000,5957.847399,14263.000000,10352.540000,3.000000,829.000000,4.000000,57.000000,NaN
std,NaN,0.000423,0.000572,8.362627,2.820563,1.035846e+05,1819.270573,3881.283826,715.400954,825.050696,2075.738064,0.654690,109.442465,0.530649,14.168367,NaN

In [8]:
report_lines = []

df_operate = df_browser.copy()

df_operate = df_operate[
    ~(df_operate['Time'] == '')
    & (df_operate['Operator'] == 'AT&T')
    & (df_operate['Location'] == 'Bowl')
    # & (df_dl_ca_browsing['String_Band'].str.contains('b2', na=False))
].copy()

df_operate = df_operate[
    ~(df_operate['Time'] == '')
    # & (
    #     (df_operate['Browsing Duration'] >= df_operate['Browsing Duration'].quantile(0.75))
    #     | (df_operate['Time To First Byte'] >= df_operate['Time To First Byte'].quantile(0.75))
    # )
    # & (df_operate['Time To First Byte'] ==  11581)
    
].copy()

ca_counts = df_operate[[
    # 'timeslot_interval', 
    # 'Time To First Byte',
    # 'Host', 
    # 'Size Of Webpage', 
    # 'Operator_QP', 
    'Time', 
    # 'Time', 'Timestamp Metric',
    'Latitude', 'Longitude', 
    # 'Throughput', 'IP Throughput',
    # 'String_Band', 'String_ARFCN',
    # 'Technology',
    'Data Technology Reporting',
    'Browsing Duration',
    # 'Size Of Webpage', 'Host'
]].value_counts(dropna=False).sort_index().to_string()

report_lines.append(ca_counts)


final_report = "\n".join(report_lines)
print(final_report)

# Save to the text file
# (OUTPUT_DIR / 'ATT_slower-than-median.txt').write_text(final_report, encoding='utf-8')

Time                     Latitude   Longitude   Data Technology Reporting                    Browsing Duration
2025-11-08 20:16:22.841  41.697944  -86.234503  LTE                                          NaN                  1
2025-11-08 20:16:54.077  41.697947  -86.234540  5G EN-DC, LTE                                NaN                  1
2025-11-08 20:17:05.316  41.697952  -86.234533  LTE                                          NaN                  1
2025-11-08 20:17:26.609  41.697951  -86.234515  LTE                                          NaN                  1
2025-11-08 20:17:57.939  41.697953  -86.234512  LTE, LTE 2CCA                                NaN                  1
2025-11-08 20:18:09.132  41.697948  -86.234506  LTE                                          NaN                  1
2025-11-08 20:18:20.322  41.697957  -86.234516  LTE                                          NaN                  1
2025-11-08 20:19:51.600  41.697956  -86.234496  5G EN-DC, LTE                                NaN                  1
2025-11-08 20:21:22.873  41.697951  -86.234501  5G EN-DC, LTE                                NaN                  1
2025-11-08 20:22:54.085  41.697937  -86.234489  5G EN-DC, LTE, LTE 2CCA, LTE 3CCA, LTE 4CCA  NaN                  1
2025-11-08 20:23:05.261  41.697937  -86.234489  LTE                                          NaN                  1
2025-11-08 20:23:16.357  41.697938  -86.234484  LTE 3CCA, LTE 4CCA, LTE, LTE 2CCA            9.945                1
2025-11-08 20:24:28.337  41.697943  -86.234489  5G EN-DC, LTE, LTE 2CCA, LTE 3CCA            11.734               1
2025-11-08 20:24:42.689  41.697944  -86.234492  LTE 4CCA, LTE 3CCA, LTE, LTE 2CCA            13.198               1
2025-11-08 20:24:52.937  41.697943  -86.234492  5G EN-DC, LTE, LTE 2CCA, LTE 3CCA            9.093                1
2025-11-08 20:25:19.280  41.697936  -86.234495  5G EN-DC, LTE, LTE 3CCA, LTE 4CCA            25.198               1
2025-11-08 20:25:38.404  41.697936  -86.234496  LTE 3CCA, LTE 4CCA, LTE, LTE 2CCA            17.921               1
2025-11-08 20:25:48.705  41.697936  -86.234497  LTE, LTE 2CCA, LTE 3CCA                      9.147                1
2025-11-08 20:26:12.496  41.697939  -86.234495  LTE, LTE 2CCA, LTE 3CCA                      22.538               1
2025-11-08 20:26:52.411  41.697941  -86.234495  LTE                                          38.788               1
2025-11-08 20:27:03.676  41.697941  -86.234495  LTE                                          NaN                  1
2025-11-08 20:27:38.265  41.697941  -86.234504  LTE, LTE 2CCA, LTE 3CCA, LTE 4CCA            33.359               1
2025-11-08 20:27:54.991  41.697942  -86.234501  5G EN-DC, LTE, LTE 2CCA                      15.507               1
2025-11-08 20:28:23.607  41.697941  -86.234498  LTE 4CCA, LTE 3CCA, LTE 2CCA, LTE            27.478               1
2025-11-08 20:29:21.757  41.697945  -86.234507  LTE 4CCA, LTE 3CCA, 5G EN-DC, LTE, LTE 2CCA  22.443               1
2025-11-08 20:30:49.675  41.697939  -86.234511  NaN                                          3.692                1
2025-11-08 20:30:53.942  41.697939  -86.234511  NaN                                          3.112                1
2025-11-08 20:31:00.075  41.697939  -86.234510  NaN                                          4.878                1
2025-11-08 20:31:04.166  41.697943  -86.234516  NaN                                          2.942                1
2025-11-08 20:31:07.076  41.697943  -86.234516  NaN                                          1.662                1
2025-11-08 20:31:10.665  41.697945  -86.234516  NaN                                          2.351                1
2025-11-08 20:32:41.909  41.697933  -86.234523  NaN                                          NaN                  1
2025-11-08 20:32:59.150  41.697932  -86.234523  NaN                                          16.015               1
2025-11-08 20:33:02.494  41.697935  -86.234520  NaN                                          2.093                1
2025-11-08 20:33:11.194  41.697932  -86.234501  NaN                                          7.483                1
2025-11-08 20:33:17.434  41.697930  -86.234497  NaN                                          4.993                1
2025-11-08 20:33:23.649  41.697940  -86.234510  NaN                                          4.919                1
2025-11-08 20:34:27.490  41.697942  -86.234514  NaN                                          2.823                1
2025-11-08 20:34:31.369  41.697942  -86.234514  NaN                                          2.707                1
2025-11-08 20:34:36.507  41.697942  -86.234514  NaN                                          3.980                1
2025-11-08 20:34:40.321  41.697942  -86.234517  NaN                                          2.581                1
2025-11-08 20:34:44.855  41.697942  -86.234517  NaN                                          3.380                1
2025-11-08 20:34:47.837  41.697942  -86.234519  NaN                                          1.837                1
2025-11-08 20:34:52.739  41.697941  -86.234519  NaN                                          3.552                1
2025-11-08 20:35:01.311  41.697940  -86.234518  NaN                                          7.302                1
2025-11-08 20:35:06.067  41.697939  -86.234518  NaN                                          3.551                1
2025-11-08 20:35:12.012  41.697939  -86.234519  NaN                                          4.777                1
2025-11-08 20:35:17.463  41.697937  -86.234522  NaN                                          4.276                1
2025-11-08 20:35:23.055  41.697937  -86.234522  NaN                                          4.451                1
2025-11-08 20:39:29.479  41.697954  -86.234804  NaN                                          NaN                  1
2025-11-08 20:39:49.890  41.697954  -86.234801  NaN                                          19.275               1
2025-11-08 20:39:59.965  41.697953  -86.234799  NaN                                          8.826                1
2025-11-08 20:40:04.106  41.697952  -86.234798  NaN                                          2.981                1
2025-11-08 20:40:10.896  41.697949  -86.234795  NaN                                          5.563                1
2025-11-08 20:40:16.887  41.697948  -86.234793  NaN                                          4.827                1
2025-11-08 20:41:48.099  41.697942  -86.234783  NaN                                          NaN                  1
2025-11-08 20:43:19.303  41.697926  -86.234766  NaN                                          NaN                  1
2025-11-08 20:43:36.603  41.697926  -86.234766  NaN                                          16.036               1
2025-11-08 20:43:42.726  41.697924  -86.234767  NaN                                          4.948                1
2025-11-08 20:43:47.609  41.697924  -86.234769  NaN                                          3.737                1
2025-11-08 20:43:56.078  41.697924  -86.234769  NaN                                          7.296                1
2025-11-08 20:44:57.197  41.697939  -86.234784  NaN                                          10.494               1
2025-11-08 20:45:00.567  41.697938  -86.234784  NaN                                          2.238                1
2025-11-08 20:45:04.505  41.697934  -86.234786  NaN                                          2.807                1
2025-11-08 20:45:09.683  41.697933  -86.234783  NaN                                          4.033                1
2025-11-08 20:45:18.087  41.697934  -86.234784  NaN                                          7.252                1
2025-11-08 20:45:21.721  41.697934  -86.234784  NaN                                          2.490                1
2025-11-08 20:45:31.040  41.697934  -86.234781  NaN                                          8.129                1
2025-11-08 20:45:45.644  41.697933  -86.234821  NaN                                          13.471               1
2025-11-08 20:45:54.033  41.697942  -86.234831  NaN                                          7.240                1
2025-11-08 20:46:00.759  41.697943  -86.234828  NaN                                          5.567                1
2025-11-08 20:46:07.582  41.697943  -86.234827  NaN                                          5.673                1
2025-11-08 20:46:15.725  41.697937  -86.234814  NaN                                          6.990                1
2025-11-08 20:47:54.747  41.697931  -86.234827  NaN                                          11.017               1
2025-11-08 20:47:58.559  41.697931  -86.234827  NaN                                          2.644                1
2025-11-08 20:48:04.005  41.697932  -86.234826  NaN                                          4.310                1
2025-11-08 20:48:07.851  41.697936  -86.234824  NaN                                          2.666                1
2025-11-08 20:48:24.865  41.697935  -86.234823  NaN                                          15.785               1
2025-11-08 20:48:28.740  41.697935  -86.234822  NaN                                          2.659                1
2025-11-08 20:48:38.874  41.697955  -86.234788  NaN                                          8.987                1
2025-11-08 20:48:48.689  41.697954  -86.234787  NaN                                          8.550                1
2025-11-08 20:48:52.498  41.697954  -86.234789  NaN                                          2.638                1
2025-11-08 20:49:01.240  41.697958  -86.234790  NaN                                          7.493                1
2025-11-08 20:49:06.329  41.697959  -86.234797  NaN                                          3.945                1
2025-11-08 20:49:15.427  41.697960  -86.234798  NaN                                          7.828                1
2025-11-08 20:49:51.872  41.697956  -86.234800  NaN                                          4.439                1
2025-11-08 20:49:57.592  41.697956  -86.234800  NaN                                          4.480                1
2025-11-08 20:50:04.812  41.697955  -86.234800  NaN                                          NaN                  1
2025-11-08 20:50:33.336  41.697951  -86.234798  NaN                                          3.112                1
2025-11-08 20:56:20.094  41.698846  -86.234511  NaN                                          19.976               1
2025-11-08 20:56:40.904  41.698844  -86.234508  NaN                                          19.634               1
2025-11-08 20:56:52.672  41.698857  -86.234527  NaN                                          10.638               1
2025-11-08 20:57:10.706  41.698851  -86.234517  NaN                                          16.890               1
2025-11-08 20:57:25.942  41.698850  -86.234514  NaN                                          14.066               1
2025-11-08 20:57:30.003  41.698847  -86.234512  NaN                                          2.896                1
2025-11-08 20:58:13.113  41.698844  -86.234506  NaN                                          41.970               1
2025-11-08 20:59:44.318  41.698854  -86.234517  NaN                                          NaN                  1
2025-11-08 20:59:53.498  41.698853  -86.234515  NaN                                          7.952                1
2025-11-08 21:00:25.880  41.698854  -86.234515  NaN                                          31.127               1
2025-11-08 21:00:46.915  41.698851  -86.234513  NaN                                          19.861               1
2025-11-08 21:01:18.390  41.698846  -86.234511  NaN                                          30.334               1
2025-11-08 21:02:49.614  41.698851  -86.234514  NaN                                          9.409                1
2025-11-08 21:03:20.863  41.698850  -86.234517  NaN                                          NaN                  1
2025-11-08 21:03:38.142  41.698846  -86.234513  NaN                                          16.127               1
2025-11-08 21:03:42.855  41.698846  -86.234513  NaN                                          3.471                1
2025-11-08 21:03:55.232  41.698846  -86.234513  NaN                                          11.126               1
2025-11-08 21:03:59.448  41.698846  -86.234513  NaN                                          3.015                1
2025-11-08 21:05:30.689  41.698849  -86.234513  NaN                                          NaN                  1
2025-11-08 21:06:56.755  41.698844  -86.234506  NaN                                          84.879               1
2025-11-08 21:07:15.488  41.698844  -86.234505  NaN                                          17.579               1
2025-11-08 21:07:43.786  41.698845  -86.234507  NaN                                          27.032               1
2025-11-08 21:08:12.933  41.698831  -86.234491  NaN                                          27.932               1
2025-11-08 21:08:29.766  41.698832  -86.234492  NaN                                          15.709               1
2025-11-08 21:19:00.164  41.697947  -86.233412  NaN                                          10.654               1
2025-11-08 21:19:11.326  41.697959  -86.233386  NaN                                          10.024               1
2025-11-08 21:19:23.319  41.697953  -86.233392  NaN                                          10.855               1
2025-11-08 21:19:56.489  41.697933  -86.233408  NaN                                          32.009               1
2025-11-08 21:20:09.006  41.697934  -86.233408  NaN                                          11.348               1
2025-11-08 21:20:15.667  41.697935  -86.233408  NaN                                          5.479                1
2025-11-08 21:21:04.393  41.697953  -86.233402  NaN                                          47.565               1
2025-11-08 21:21:21.636  41.697951  -86.233412  NaN                                          16.073               1
2025-11-08 21:21:29.945  41.697948  -86.233418  NaN                                          7.135                1
2025-11-08 21:21:45.338  41.697943  -86.233407  NaN                                          14.184               1
2025-11-08 21:21:56.661  41.697937  -86.233413  NaN                                          10.176               1
2025-11-08 21:22:34.570  41.697939  -86.233413  NaN                                          36.736               1
2025-11-08 21:24:13.783  41.697950  -86.233383  NaN                                          4.726                1
2025-11-08 21:24:19.208  41.697951  -86.233383  NaN                                          4.189                1
2025-11-08 21:24:23.552  41.697950  -86.233383  NaN                                          3.196                1
2025-11-08 21:24:27.936  41.697950  -86.233383  NaN                                          3.155                1
2025-11-08 21:24:37.286  41.697949  -86.233384  NaN                                          8.102                1
2025-11-08 21:24:41.955  41.697948  -86.233384  NaN                                          3.511                1
2025-11-08 21:26:13.173  41.697942  -86.233386  NaN                                          NaN                  1
2025-11-08 21:26:19.860  41.697941  -86.233388  NaN                                          5.522                1
2025-11-08 21:26:32.753  41.697942  -86.233391  NaN                                          11.656               1
2025-11-08 21:26:40.206  41.697941  -86.233391  NaN                                          6.321                1
2025-11-08 21:26:44.691  41.697941  -86.233391  NaN                                          3.298                1
2025-11-08 21:26:55.289  41.697942  -86.233395  NaN                                          9.398                1
2025-11-08 21:32:45.999  41.698903  -86.233444  NaN                                          10.644               1
2025-11-08 21:32:48.848  41.698903  -86.233444  NaN                                          1.696                1
2025-11-08 21:32:58.296  41.698901  -86.233444  NaN                                          8.223                1
2025-11-08 21:33:01.560  41.698901  -86.233442  NaN                                          2.118                1
2025-11-08 21:33:05.607  41.698901  -86.233440  NaN                                          2.871                1
2025-11-08 21:33:08.512  41.698900  -86.233440  NaN                                          1.717                1
2025-11-08 21:33:14.963  41.698910  -86.233432  NaN                                          5.200                1
2025-11-08 21:33:22.801  41.698905  -86.233436  NaN                                          6.623                1
2025-11-08 21:33:25.524  41.698906  -86.233440  NaN                                          1.577                1
2025-11-08 21:33:31.271  41.698905  -86.233442  NaN                                          4.490                1
2025-11-08 21:33:36.898  41.698902  -86.233442  NaN                                          4.415                1
2025-11-08 21:33:41.138  41.698898  -86.233440  NaN                                          3.068                1
2025-11-08 21:35:13.337  41.698901  -86.233448  NaN                                          5.407                1
2025-11-08 21:35:15.577  41.698901  -86.233448  NaN                                          1.065                1
2025-11-08 21:35:22.234  41.698902  -86.233447  NaN                                          5.510                1
2025-11-08 21:35:25.906  41.698902  -86.233446  NaN                                          2.461                1
2025-11-08 21:35:30.934  41.698908  -86.233443  NaN                                          3.848                1
2025-11-08 21:35:34.370  41.698907  -86.233443  NaN                                          2.183                1
2025-11-08 21:37:05.597  41.698899  -86.233449  NaN                                          NaN                  1
2025-11-08 21:37:13.614  41.698900  -86.233449  NaN                                          6.788                1
2025-11-08 21:37:17.510  41.698900  -86.233449  NaN                                          2.745                1
2025-11-08 21:37:23.412  41.698899  -86.233448  NaN                                          4.761                1
2025-11-08 21:37:29.703  41.698896  -86.233449  NaN                                          5.137                1
2025-11-08 21:37:36.168  41.698898  -86.233452  NaN                                          5.180                1

In [9]:
# Correlate df_browser and df_sigcap

# 1. Handle Timezones
# Browser 'Time' is likely naive local time (ET). Localize it.
if df_browser['Time'].dt.tz is None:
    df_browser['Time'] = df_browser['Time'].dt.tz_localize('US/Eastern', ambiguous='infer')

# Sigcap 'timestamp' is already tz-aware. Convert both to UTC for safe merging.
df_browser['Time_utc'] = df_browser['Time'].dt.tz_convert('UTC')
df_sigcap['timestamp_utc'] = df_sigcap['timestamp'].dt.tz_convert('UTC')

# 2. Merge
# We want to bring 'network_type*' and 'wifi_connected_primary_freq_mhz' from sigcap to browser
cols_to_merge = ['timestamp_utc', 'operator', 'network_type*', 'wifi_connected_primary_freq_mhz', 'Location']

cols_to_merge.append('uuid')
df_browser_merged = pd.merge_asof(
    df_browser,
    df_sigcap[cols_to_merge],
    left_on='Time_utc',
    right_on='timestamp_utc',
    by='uuid',
    direction='nearest',
    tolerance=pd.Timedelta('10s')
)

# 3. Cleanup
df_browser_merged = df_browser_merged.drop(columns=['timestamp_utc', 'Time_utc'])

# Rename Location columns for clarity after merge
df_browser_merged = df_browser_merged.rename(columns={'Location_x': 'Location', 'Location_y': 'Location_sigcap'})

conditions = [
    (df_browser_merged['wifi_connected_primary_freq_mhz'].between(5000, 5925, inclusive='both')),
    (df_browser_merged['wifi_connected_primary_freq_mhz'] > 5925),
    (df_browser_merged['wifi_connected_primary_freq_mhz'] < 5000)
]
choices = ['Wi-Fi 5', 'Wi-Fi 6', 'Wi-Fi 2.4']
df_browser_merged['operator'] = np.select(conditions, choices, default=df_browser_merged['operator'])

# Check for Location mismatches
df_mismatched_Locations = df_browser_merged[df_browser_merged['Location'] != df_browser_merged['Location_sigcap']]
print(f"Rows with mismatched Locations: {df_mismatched_Locations.shape[0]}")
display(df_mismatched_Locations)

# Display result
print(f"Merged shape: {df_browser_merged.shape}")
display(df_browser_merged)
df_browser_merged.to_csv(OUTPUT_DIR / 'df_browser_merged_gd5.csv', index=False)

Rows with mismatched Locations: 0

Empty DataFrame
Columns: [Time, Latitude, Longitude, Unit, Operator, Browsing Duration, Download Duration, IP Throughput, Access Duration, Time To First Byte, Kbytes In First Second, Round Trip Time (RTT), Size Of Webpage, Number of Redirections, Browser, Page Complete Criterion, Number of Resources, Number of Resources not loaded, Number of Images, APN, Primary DNS, IP, Resolved Target IP, Host, Protocol, Operation, AP Type, AP Profile Name, Test Name, Direction, Test Status, Location, uuid, Data Technology Reporting, operator, network_type*, wifi_connected_primary_freq_mhz, Location_sigcap]
Index: []

[0 rows x 38 columns]

Merged shape: (773, 38)

,Time,Latitude,Longitude,Unit,Operator,Browsing Duration,Download Duration,IP Throughput,Access Duration,Time To First Byte,...,Test Name,Direction,Test Status,Location,uuid,Data Technology Reporting,operator,network_type*,wifi_connected_primary_freq_mhz,Location_sigcap
0,2025-11-08 20:13:16.526000-05:00,41.697948,-86.233408,QualiPoc_619529,T-Mobile,23.200,9.124,2146.291977,264.0,595.0,...,Browsing,Downlink,Completed,Bowl,64957d65,NaN,T-Mobile,NR,NaN,Bowl
1,2025-11-08 20:13:31.012000-05:00,41.697949,-86.233401,QualiPoc_619529,T-Mobile,13.194,8.210,1214.959318,2194.0,2464.0,...,Browsing,Downlink,Completed,Bowl,64957d65,NaN,T-Mobile,NR,NaN,Bowl
2,2025-11-08 20:13:56.509000-05:00,41.697949,-86.233402,QualiPoc_619529,T-Mobile,24.312,13.908,964.000575,NaN,NaN,...,Browsing,Downlink,Completed,Bowl,64957d65,NaN,T-Mobile,NR,NaN,Bowl
3,2025-11-08 20:14:04.497000-05:00,41.697950,-86.233402,QualiPoc_619529,T-Mobile,6.685,4.399,2274.640600,560.0,1108.0,...,Browsing,Downlink,Completed,Bowl,64957d65,NaN,T-Mobile,NR,NaN,Bowl
4,2025-11-08 20:14:08.448000-05:00,41.697949,-86.233402,QualiPoc_619529,T-Mobile,2.673,1.969,4318.561706,341.0,633.0,...,Browsing,Downlink,Completed,Bowl,64957d65,NaN,T-Mobile,NR,NaN,Bowl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,2025-11-08 22:17:20.409000-05:00,41.699353,-86.232932,QualiPoc_396840,Verizon,8.378,1.038,44175.606936,393.0,539.0,...,Browsing,Downlink,Completed,Concourse,7c36e7df,NaN,Wi-Fi 6,LTE,6215.0,Concourse
769,2025-11-08 22:17:24.819000-05:00,41.699353,-86.232932,QualiPoc_396840,Verizon,3.220,1.412,5402.189804,340.0,1707.0,...,Browsing,Downlink,Completed,Concourse,7c36e7df,NaN,Wi-Fi 6,LTE,6215.0,Concourse
770,2025-11-08 22:17:29.792000-05:00,41.699353,-86.232932,QualiPoc_396840,Verizon,3.754,1.192,16703.449664,316.0,387.0,...,Browsing,Downlink,Completed,Concourse,7c36e7df,NaN,Wi-Fi 6,LTE,6215.0,Concourse
771,2025-11-08 22:17:35.594000-05:00,41.699351,-86.232934,QualiPoc_396840,Verizon,4.523,0.257,232690.770428,310.0,507.0,...,Browsing,Downlink,Completed,Concourse,7c36e7df,NaN,Wi-Fi 6,LTE,6215.0,Concourse
772,2025-11-08 22:17:40.372000-05:00,41.699350,-86.232935,QualiPoc_396840,Verizon,3.620,0.267,151803.655431,407.0,553.0,...,Browsing,Downlink,Completed,Concourse,7c36e7df,NaN,Wi-Fi 6,LTE,6215.0,Concourse

### plc, checks

In [10]:
df_browser_merged.columns

Index(['Time', 'Latitude', 'Longitude', 'Unit', 'Operator',
       'Browsing Duration', 'Download Duration', 'IP Throughput',
       'Access Duration', 'Time To First Byte', 'Kbytes In First Second',
       'Round Trip Time (RTT)', 'Size Of Webpage', 'Number of Redirections',
       'Browser', 'Page Complete Criterion', 'Number of Resources',
       'Number of Resources not loaded', 'Number of Images', 'APN',
       'Primary DNS', 'IP', 'Resolved Target IP', 'Host', 'Protocol',
       'Operation', 'AP Type', 'AP Profile Name', 'Test Name', 'Direction',
       'Test Status', 'Location', 'uuid', 'Data Technology Reporting',
       'operator', 'network_type*', 'wifi_connected_primary_freq_mhz',
       'Location_sigcap'],
      dtype='str')

In [11]:
report_lines = []

df_operate = df_browser_merged.copy()

df_operate = df_operate[
    ~(df_operate['Time'] == '')
    & (df_operate['Operator'] == 'AT&T')
    & (df_operate['Location'] == 'Bowl')
    # & (df_dl_ca_browsing['String_Band'].str.contains('b2', na=False))
].copy()

df_operate = df_operate[
    ~(df_operate['Time'] == '')
    # & (
    #     (df_operate['Browsing Duration'] >= df_operate['Browsing Duration'].quantile(0.75))
    #     | (df_operate['Time To First Byte'] >= df_operate['Time To First Byte'].quantile(0.75))
    # )
    # & (df_operate['Time To First Byte'] ==  11581)
    
].copy()

ca_counts = df_operate[[
    # 'timeslot_interval', 
    # 'Time To First Byte',
    # 'Host', 
    # 'Size Of Webpage', 
    # 'Operator_QP', 
    'Time', 
    # 'Time', 'Timestamp Metric',
    'Latitude', 'Longitude', 
    # 'Throughput', 'IP Throughput',
    # 'String_Band', 'String_ARFCN',
    # 'Technology',
    'Data Technology Reporting',
    'Browsing Duration',
    # 'Size Of Webpage', 'Host'
]].value_counts(dropna=False).sort_index().to_string()

report_lines.append(ca_counts)


final_report = "\n".join(report_lines)
print(final_report)

# Save to the text file
# (OUTPUT_DIR / 'ATT_slower-than-median.txt').write_text(final_report, encoding='utf-8')

Time                              Latitude   Longitude   Data Technology Reporting                    Browsing Duration
2025-11-08 20:16:22.841000-05:00  41.697944  -86.234503  LTE                                          NaN                  1
2025-11-08 20:16:54.077000-05:00  41.697947  -86.234540  5G EN-DC, LTE                                NaN                  1
2025-11-08 20:17:05.316000-05:00  41.697952  -86.234533  LTE                                          NaN                  1
2025-11-08 20:17:26.609000-05:00  41.697951  -86.234515  LTE                                          NaN                  1
2025-11-08 20:17:57.939000-05:00  41.697953  -86.234512  LTE, LTE 2CCA                                NaN                  1
2025-11-08 20:18:09.132000-05:00  41.697948  -86.234506  LTE                                          NaN                  1
2025-11-08 20:18:20.322000-05:00  41.697957  -86.234516  LTE                                          NaN                  1
2025-11-08 20:19:51.600000-05:00  41.697956  -86.234496  5G EN-DC, LTE                                NaN                  1
2025-11-08 20:21:22.873000-05:00  41.697951  -86.234501  5G EN-DC, LTE                                NaN                  1
2025-11-08 20:22:54.085000-05:00  41.697937  -86.234489  5G EN-DC, LTE, LTE 2CCA, LTE 3CCA, LTE 4CCA  NaN                  1
2025-11-08 20:23:05.261000-05:00  41.697937  -86.234489  LTE                                          NaN                  1
2025-11-08 20:23:16.357000-05:00  41.697938  -86.234484  LTE 3CCA, LTE 4CCA, LTE, LTE 2CCA            9.945                1
2025-11-08 20:24:28.337000-05:00  41.697943  -86.234489  5G EN-DC, LTE, LTE 2CCA, LTE 3CCA            11.734               1
2025-11-08 20:24:42.689000-05:00  41.697944  -86.234492  LTE 4CCA, LTE 3CCA, LTE, LTE 2CCA            13.198               1
2025-11-08 20:24:52.937000-05:00  41.697943  -86.234492  5G EN-DC, LTE, LTE 2CCA, LTE 3CCA            9.093                1
2025-11-08 20:25:19.280000-05:00  41.697936  -86.234495  5G EN-DC, LTE, LTE 3CCA, LTE 4CCA            25.198               1
2025-11-08 20:25:38.404000-05:00  41.697936  -86.234496  LTE 3CCA, LTE 4CCA, LTE, LTE 2CCA            17.921               1
2025-11-08 20:25:48.705000-05:00  41.697936  -86.234497  LTE, LTE 2CCA, LTE 3CCA                      9.147                1
2025-11-08 20:26:12.496000-05:00  41.697939  -86.234495  LTE, LTE 2CCA, LTE 3CCA                      22.538               1
2025-11-08 20:26:52.411000-05:00  41.697941  -86.234495  LTE                                          38.788               1
2025-11-08 20:27:03.676000-05:00  41.697941  -86.234495  LTE                                          NaN                  1
2025-11-08 20:27:38.265000-05:00  41.697941  -86.234504  LTE, LTE 2CCA, LTE 3CCA, LTE 4CCA            33.359               1
2025-11-08 20:27:54.991000-05:00  41.697942  -86.234501  5G EN-DC, LTE, LTE 2CCA                      15.507               1
2025-11-08 20:28:23.607000-05:00  41.697941  -86.234498  LTE 4CCA, LTE 3CCA, LTE 2CCA, LTE            27.478               1
2025-11-08 20:29:21.757000-05:00  41.697945  -86.234507  LTE 4CCA, LTE 3CCA, 5G EN-DC, LTE, LTE 2CCA  22.443               1
2025-11-08 20:30:49.675000-05:00  41.697939  -86.234511  NaN                                          3.692                1
2025-11-08 20:30:53.942000-05:00  41.697939  -86.234511  NaN                                          3.112                1
2025-11-08 20:31:00.075000-05:00  41.697939  -86.234510  NaN                                          4.878                1
2025-11-08 20:31:04.166000-05:00  41.697943  -86.234516  NaN                                          2.942                1
2025-11-08 20:31:07.076000-05:00  41.697943  -86.234516  NaN                                          1.662                1
2025-11-08 20:31:10.665000-05:00  41.697945  -86.234516  NaN                                          2.351                1
2025-11-08 20:32:41.909000-05:00  41.697933  -86.234523  NaN                                          NaN                  1
2025-11-08 20:32:59.150000-05:00  41.697932  -86.234523  NaN                                          16.015               1
2025-11-08 20:33:02.494000-05:00  41.697935  -86.234520  NaN                                          2.093                1
2025-11-08 20:33:11.194000-05:00  41.697932  -86.234501  NaN                                          7.483                1
2025-11-08 20:33:17.434000-05:00  41.697930  -86.234497  NaN                                          4.993                1
2025-11-08 20:33:23.649000-05:00  41.697940  -86.234510  NaN                                          4.919                1
2025-11-08 20:34:27.490000-05:00  41.697942  -86.234514  NaN                                          2.823                1
2025-11-08 20:34:31.369000-05:00  41.697942  -86.234514  NaN                                          2.707                1
2025-11-08 20:34:36.507000-05:00  41.697942  -86.234514  NaN                                          3.980                1
2025-11-08 20:34:40.321000-05:00  41.697942  -86.234517  NaN                                          2.581                1
2025-11-08 20:34:44.855000-05:00  41.697942  -86.234517  NaN                                          3.380                1
2025-11-08 20:34:47.837000-05:00  41.697942  -86.234519  NaN                                          1.837                1
2025-11-08 20:34:52.739000-05:00  41.697941  -86.234519  NaN                                          3.552                1
2025-11-08 20:35:01.311000-05:00  41.697940  -86.234518  NaN                                          7.302                1
2025-11-08 20:35:06.067000-05:00  41.697939  -86.234518  NaN                                          3.551                1
2025-11-08 20:35:12.012000-05:00  41.697939  -86.234519  NaN                                          4.777                1
2025-11-08 20:35:17.463000-05:00  41.697937  -86.234522  NaN                                          4.276                1
2025-11-08 20:35:23.055000-05:00  41.697937  -86.234522  NaN                                          4.451                1
2025-11-08 20:39:29.479000-05:00  41.697954  -86.234804  NaN                                          NaN                  1
2025-11-08 20:39:49.890000-05:00  41.697954  -86.234801  NaN                                          19.275               1
2025-11-08 20:39:59.965000-05:00  41.697953  -86.234799  NaN                                          8.826                1
2025-11-08 20:40:04.106000-05:00  41.697952  -86.234798  NaN                                          2.981                1
2025-11-08 20:40:10.896000-05:00  41.697949  -86.234795  NaN                                          5.563                1
2025-11-08 20:40:16.887000-05:00  41.697948  -86.234793  NaN                                          4.827                1
2025-11-08 20:41:48.099000-05:00  41.697942  -86.234783  NaN                                          NaN                  1
2025-11-08 20:43:19.303000-05:00  41.697926  -86.234766  NaN                                          NaN                  1
2025-11-08 20:43:36.603000-05:00  41.697926  -86.234766  NaN                                          16.036               1
2025-11-08 20:43:42.726000-05:00  41.697924  -86.234767  NaN                                          4.948                1
2025-11-08 20:43:47.609000-05:00  41.697924  -86.234769  NaN                                          3.737                1
2025-11-08 20:43:56.078000-05:00  41.697924  -86.234769  NaN                                          7.296                1
2025-11-08 20:44:57.197000-05:00  41.697939  -86.234784  NaN                                          10.494               1
2025-11-08 20:45:00.567000-05:00  41.697938  -86.234784  NaN                                          2.238                1
2025-11-08 20:45:04.505000-05:00  41.697934  -86.234786  NaN                                          2.807                1
2025-11-08 20:45:09.683000-05:00  41.697933  -86.234783  NaN                                          4.033                1
2025-11-08 20:45:18.087000-05:00  41.697934  -86.234784  NaN                                          7.252                1
2025-11-08 20:45:21.721000-05:00  41.697934  -86.234784  NaN                                          2.490                1
2025-11-08 20:45:31.040000-05:00  41.697934  -86.234781  NaN                                          8.129                1
2025-11-08 20:45:45.644000-05:00  41.697933  -86.234821  NaN                                          13.471               1
2025-11-08 20:45:54.033000-05:00  41.697942  -86.234831  NaN                                          7.240                1
2025-11-08 20:46:00.759000-05:00  41.697943  -86.234828  NaN                                          5.567                1
2025-11-08 20:46:07.582000-05:00  41.697943  -86.234827  NaN                                          5.673                1
2025-11-08 20:46:15.725000-05:00  41.697937  -86.234814  NaN                                          6.990                1
2025-11-08 20:47:54.747000-05:00  41.697931  -86.234827  NaN                                          11.017               1
2025-11-08 20:47:58.559000-05:00  41.697931  -86.234827  NaN                                          2.644                1
2025-11-08 20:48:04.005000-05:00  41.697932  -86.234826  NaN                                          4.310                1
2025-11-08 20:48:07.851000-05:00  41.697936  -86.234824  NaN                                          2.666                1
2025-11-08 20:48:24.865000-05:00  41.697935  -86.234823  NaN                                          15.785               1
2025-11-08 20:48:28.740000-05:00  41.697935  -86.234822  NaN                                          2.659                1
2025-11-08 20:48:38.874000-05:00  41.697955  -86.234788  NaN                                          8.987                1
2025-11-08 20:48:48.689000-05:00  41.697954  -86.234787  NaN                                          8.550                1
2025-11-08 20:48:52.498000-05:00  41.697954  -86.234789  NaN                                          2.638                1
2025-11-08 20:49:01.240000-05:00  41.697958  -86.234790  NaN                                          7.493                1
2025-11-08 20:49:06.329000-05:00  41.697959  -86.234797  NaN                                          3.945                1
2025-11-08 20:49:15.427000-05:00  41.697960  -86.234798  NaN                                          7.828                1
2025-11-08 20:49:51.872000-05:00  41.697956  -86.234800  NaN                                          4.439                1
2025-11-08 20:49:57.592000-05:00  41.697956  -86.234800  NaN                                          4.480                1
2025-11-08 20:50:04.812000-05:00  41.697955  -86.234800  NaN                                          NaN                  1
2025-11-08 20:50:33.336000-05:00  41.697951  -86.234798  NaN                                          3.112                1
2025-11-08 20:56:20.094000-05:00  41.698846  -86.234511  NaN                                          19.976               1
2025-11-08 20:56:40.904000-05:00  41.698844  -86.234508  NaN                                          19.634               1
2025-11-08 20:56:52.672000-05:00  41.698857  -86.234527  NaN                                          10.638               1
2025-11-08 20:57:10.706000-05:00  41.698851  -86.234517  NaN                                          16.890               1
2025-11-08 20:57:25.942000-05:00  41.698850  -86.234514  NaN                                          14.066               1
2025-11-08 20:57:30.003000-05:00  41.698847  -86.234512  NaN                                          2.896                1
2025-11-08 20:58:13.113000-05:00  41.698844  -86.234506  NaN                                          41.970               1
2025-11-08 20:59:44.318000-05:00  41.698854  -86.234517  NaN                                          NaN                  1
2025-11-08 20:59:53.498000-05:00  41.698853  -86.234515  NaN                                          7.952                1
2025-11-08 21:00:25.880000-05:00  41.698854  -86.234515  NaN                                          31.127               1
2025-11-08 21:00:46.915000-05:00  41.698851  -86.234513  NaN                                          19.861               1
2025-11-08 21:01:18.390000-05:00  41.698846  -86.234511  NaN                                          30.334               1
2025-11-08 21:02:49.614000-05:00  41.698851  -86.234514  NaN                                          9.409                1
2025-11-08 21:03:20.863000-05:00  41.698850  -86.234517  NaN                                          NaN                  1
2025-11-08 21:03:38.142000-05:00  41.698846  -86.234513  NaN                                          16.127               1
2025-11-08 21:03:42.855000-05:00  41.698846  -86.234513  NaN                                          3.471                1
2025-11-08 21:03:55.232000-05:00  41.698846  -86.234513  NaN                                          11.126               1
2025-11-08 21:03:59.448000-05:00  41.698846  -86.234513  NaN                                          3.015                1
2025-11-08 21:05:30.689000-05:00  41.698849  -86.234513  NaN                                          NaN                  1
2025-11-08 21:06:56.755000-05:00  41.698844  -86.234506  NaN                                          84.879               1
2025-11-08 21:07:15.488000-05:00  41.698844  -86.234505  NaN                                          17.579               1
2025-11-08 21:07:43.786000-05:00  41.698845  -86.234507  NaN                                          27.032               1
2025-11-08 21:08:12.933000-05:00  41.698831  -86.234491  NaN                                          27.932               1
2025-11-08 21:08:29.766000-05:00  41.698832  -86.234492  NaN                                          15.709               1
2025-11-08 21:19:00.164000-05:00  41.697947  -86.233412  NaN                                          10.654               1
2025-11-08 21:19:11.326000-05:00  41.697959  -86.233386  NaN                                          10.024               1
2025-11-08 21:19:23.319000-05:00  41.697953  -86.233392  NaN                                          10.855               1
2025-11-08 21:19:56.489000-05:00  41.697933  -86.233408  NaN                                          32.009               1
2025-11-08 21:20:09.006000-05:00  41.697934  -86.233408  NaN                                          11.348               1
2025-11-08 21:20:15.667000-05:00  41.697935  -86.233408  NaN                                          5.479                1
2025-11-08 21:21:04.393000-05:00  41.697953  -86.233402  NaN                                          47.565               1
2025-11-08 21:21:21.636000-05:00  41.697951  -86.233412  NaN                                          16.073               1
2025-11-08 21:21:29.945000-05:00  41.697948  -86.233418  NaN                                          7.135                1
2025-11-08 21:21:45.338000-05:00  41.697943  -86.233407  NaN                                          14.184               1
2025-11-08 21:21:56.661000-05:00  41.697937  -86.233413  NaN                                          10.176               1
2025-11-08 21:22:34.570000-05:00  41.697939  -86.233413  NaN                                          36.736               1
2025-11-08 21:24:13.783000-05:00  41.697950  -86.233383  NaN                                          4.726                1
2025-11-08 21:24:19.208000-05:00  41.697951  -86.233383  NaN                                          4.189                1
2025-11-08 21:24:23.552000-05:00  41.697950  -86.233383  NaN                                          3.196                1
2025-11-08 21:24:27.936000-05:00  41.697950  -86.233383  NaN                                          3.155                1
2025-11-08 21:24:37.286000-05:00  41.697949  -86.233384  NaN                                          8.102                1
2025-11-08 21:24:41.955000-05:00  41.697948  -86.233384  NaN                                          3.511                1
2025-11-08 21:26:13.173000-05:00  41.697942  -86.233386  NaN                                          NaN                  1
2025-11-08 21:26:19.860000-05:00  41.697941  -86.233388  NaN                                          5.522                1
2025-11-08 21:26:32.753000-05:00  41.697942  -86.233391  NaN                                          11.656               1
2025-11-08 21:26:40.206000-05:00  41.697941  -86.233391  NaN                                          6.321                1
2025-11-08 21:26:44.691000-05:00  41.697941  -86.233391  NaN                                          3.298                1
2025-11-08 21:26:55.289000-05:00  41.697942  -86.233395  NaN                                          9.398                1
2025-11-08 21:32:45.999000-05:00  41.698903  -86.233444  NaN                                          10.644               1
2025-11-08 21:32:48.848000-05:00  41.698903  -86.233444  NaN                                          1.696                1
2025-11-08 21:32:58.296000-05:00  41.698901  -86.233444  NaN                                          8.223                1
2025-11-08 21:33:01.560000-05:00  41.698901  -86.233442  NaN                                          2.118                1
2025-11-08 21:33:05.607000-05:00  41.698901  -86.233440  NaN                                          2.871                1
2025-11-08 21:33:08.512000-05:00  41.698900  -86.233440  NaN                                          1.717                1
2025-11-08 21:33:14.963000-05:00  41.698910  -86.233432  NaN                                          5.200                1
2025-11-08 21:33:22.801000-05:00  41.698905  -86.233436  NaN                                          6.623                1
2025-11-08 21:33:25.524000-05:00  41.698906  -86.233440  NaN                                          1.577                1
2025-11-08 21:33:31.271000-05:00  41.698905  -86.233442  NaN                                          4.490                1
2025-11-08 21:33:36.898000-05:00  41.698902  -86.233442  NaN                                          4.415                1
2025-11-08 21:33:41.138000-05:00  41.698898  -86.233440  NaN                                          3.068                1
2025-11-08 21:35:13.337000-05:00  41.698901  -86.233448  NaN                                          5.407                1
2025-11-08 21:35:15.577000-05:00  41.698901  -86.233448  NaN                                          1.065                1
2025-11-08 21:35:22.234000-05:00  41.698902  -86.233447  NaN                                          5.510                1
2025-11-08 21:35:25.906000-05:00  41.698902  -86.233446  NaN                                          2.461                1
2025-11-08 21:35:30.934000-05:00  41.698908  -86.233443  NaN                                          3.848                1
2025-11-08 21:35:34.370000-05:00  41.698907  -86.233443  NaN                                          2.183                1
2025-11-08 21:37:05.597000-05:00  41.698899  -86.233449  NaN                                          NaN                  1
2025-11-08 21:37:13.614000-05:00  41.698900  -86.233449  NaN                                          6.788                1
2025-11-08 21:37:17.510000-05:00  41.698900  -86.233449  NaN                                          2.745                1
2025-11-08 21:37:23.412000-05:00  41.698899  -86.233448  NaN                                          4.761                1