# Project Team Members

| Prepared by | Email | Prepared for |
| :-: | :-: | :-: |
| **_Hardani Ismu Nabil_** | _hardani.ismu.n@gmail.com_ | **_ND Stadium Collaborative Project 2025/2026_** |

# Notebook Target Definition

* **GOAL** create merged app metric dataframes by merge_asof left=df_metric from QualiPoc with right=df_sigcap
* **REQUIRED** to run Ardan-2026_analysis_* notebooks
* **DATE** This is for Gameday November 11th 2026 data

# ===============================
# ===============================

# A- Setup

### A-1: Housechores

In [1]:
import os
import pathlib

import numpy as np
import pandas as pd

In [2]:
PROJECT_ROOT = pathlib.Path('.').cwd().parent # you can also do it manually, for example ~/repos/NdSta2026


print('='*50, '[DATA DIRECTORY]')
DATA_DIR = PROJECT_ROOT / "data_raw"

print(f"Project Root: {PROJECT_ROOT}")
print(f"Looking for data in: {DATA_DIR}")


print('- '*25)
print('='*50, '[OUTPUT DIRECTORY]')

# OUTPUT_DIR = PROJECT_ROOT / 'output/output_July1st_sigcapDataProcessing/sigcap-merge_gameday6' # CHANGE this into the notebook file name
OUTPUT_DIR = PROJECT_ROOT / 'data_processed'
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Project Root: {PROJECT_ROOT}")
print(f"All outputs will be in: {OUTPUT_DIR}")

================================================== [DATA DIRECTORY]
Project Root: /home/analisis/repos/NDKI_01_ForGithub_ForArtifact_wintech_2026_stadium_paper_analysis
Looking for data in: /home/analisis/repos/NDKI_01_ForGithub_ForArtifact_wintech_2026_stadium_paper_analysis/data_raw
- - - - - - - - - - - - - - - - - - - - - - - - -
================================================== [OUTPUT DIRECTORY]
Project Root: /home/analisis/repos/NDKI_01_ForGithub_ForArtifact_wintech_2026_stadium_paper_analysis
All outputs will be in: /home/analisis/repos/NDKI_01_ForGithub_ForArtifact_wintech_2026_stadium_paper_analysis/data_processed

### A-2: SigCap data for correlation

In [3]:
selected_cols = ['timestamp', 'latitude', 'longitude', 'uuid', 'operator', 'Location', 'network_type*', 'wifi_connected_primary_freq_mhz']    

df_sigcap = pd.concat([
    pd.read_csv(DATA_DIR / 'game6_sigcap_csv/20251122_sigcap_bowl_general.csv', parse_dates=['timestamp']).assign(Location='Bowl'),
    pd.read_csv(DATA_DIR / 'game6_sigcap_csv/20251122_sigcap_concourse_general.csv', parse_dates=['timestamp']).assign(Location='Concourse')
]).reset_index(drop=True)

df_sigcap = df_sigcap[selected_cols].sort_values('timestamp')
df_sigcap['uuid'] = df_sigcap['uuid'].str.slice(0, 8)
df_sigcap.to_csv(DATA_DIR / 'game6_sigcap_csv/20251122_sigcap_general.csv', index=False)
df_sigcap.to_csv(OUTPUT_DIR / '20251122_sigcap_general.csv', index=False)
print(f"Sigcap data shape: {df_sigcap.shape}")
display(df_sigcap[['uuid', 'operator']].drop_duplicates())
df_sigcap.head()

/tmp/ipykernel_29177/35759932.py:4: DtypeWarning: Columns (0: wifi_2.4_other5_ssid, 1: wifi_2.4_other5_bssid, 2: wifi_2.4_other5_standard, 3: wifi_2.4_other6_ssid, 4: wifi_2.4_other6_bssid, 5: wifi_2.4_other6_standard, 6: wifi_5_other94_ssid, 7: wifi_5_other94_bssid, 8: wifi_5_other94_standard, 9: wifi_5_other95_ssid, 10: wifi_5_other95_bssid, 11: wifi_5_other95_standard, 12: wifi_5_other96_ssid, 13: wifi_5_other96_bssid, 14: wifi_5_other96_standard, 15: wifi_5_other97_ssid, 16: wifi_5_other97_bssid, 17: wifi_5_other97_standard, 18: wifi_5_other98_ssid, 19: wifi_5_other98_bssid, 20: wifi_5_other98_standard, 21: wifi_5_other99_ssid, 22: wifi_5_other99_bssid, 23: wifi_5_other99_standard, 24: wifi_5_other100_ssid, 25: wifi_5_other100_bssid, 26: wifi_5_other100_standard, 27: wifi_5_other101_ssid, 28: wifi_5_other101_bssid, 29: wifi_5_other101_standard, 30: wifi_5_other102_ssid, 31: wifi_5_other102_bssid, 32: wifi_5_other102_standard, 33: wifi_5_other103_ssid, 34: wifi_5_other103_bssid, 35: wifi_5_other103_standard, 36: wifi_5_other104_ssid, 37: wifi_5_other104_bssid, 38: wifi_5_other104_standard, 39: wifi_5_other105_ssid, 40: wifi_5_other105_bssid, 41: wifi_5_other105_standard, 42: wifi_5_other106_ssid, 43: wifi_5_other106_bssid, 44: wifi_5_other106_standard, 45: wifi_5_other107_ssid, 46: wifi_5_other107_bssid, 47: wifi_5_other107_standard, 48: wifi_5_other108_ssid, 49: wifi_5_other108_bssid, 50: wifi_5_other108_standard, 51: wifi_5_other109_ssid, 52: wifi_5_other109_bssid, 53: wifi_5_other109_standard, 54: wifi_5_other110_ssid, 55: wifi_5_other110_bssid, 56: wifi_5_other110_standard, 57: wifi_5_other111_ssid, 58: wifi_5_other111_bssid, 59: wifi_5_other111_standard, 60: wifi_5_other112_ssid, 61: wifi_5_other112_bssid, 62: wifi_5_other112_standard, 63: wifi_5_other113_ssid, 64: wifi_5_other113_bssid, 65: wifi_5_other113_standard, 66: wifi_5_other114_ssid, 67: wifi_5_other114_bssid, 68: wifi_5_other114_standard, 69: wifi_5_other115_ssid, 70: wifi_5_other115_bssid, 71: wifi_5_other115_standard, 72: wifi_5_other116_ssid, 73: wifi_5_other116_bssid, 74: wifi_5_other116_standard, 75: wifi_5_other117_ssid, 76: wifi_5_other117_bssid, 77: wifi_5_other117_standard, 78: wifi_5_other118_ssid, 79: wifi_5_other118_bssid, 80: wifi_5_other118_standard, 81: wifi_5_other119_ssid, 82: wifi_5_other119_bssid, 83: wifi_5_other119_standard, 84: wifi_5_other120_ssid, 85: wifi_5_other120_bssid, 86: wifi_5_other120_standard, 87: wifi_5_other121_ssid, 88: wifi_5_other121_bssid, 89: wifi_5_other121_standard, 90: wifi_5_other122_ssid, 91: wifi_5_other122_bssid, 92: wifi_5_other122_standard, 93: wifi_5_other123_ssid, 94: wifi_5_other123_bssid, 95: wifi_5_other123_standard, 96: wifi_5_other124_ssid, 97: wifi_5_other124_bssid, 98: wifi_5_other124_standard, 99: wifi_5_other125_ssid, 100: wifi_5_other125_bssid, 101: wifi_5_other125_standard, 102: wifi_5_other126_ssid, 103: wifi_5_other126_bssid, 104: wifi_5_other126_standard, 105: wifi_5_other127_ssid, 106: wifi_5_other127_bssid, 107: wifi_5_other127_standard, 108: wifi_5_other128_ssid, 109: wifi_5_other128_bssid, 110: wifi_5_other128_standard, 111: wifi_5_other129_ssid, 112: wifi_5_other129_bssid, 113: wifi_5_other129_standard, 114: wifi_6_other31_ssid, 115: wifi_6_other31_bssid, 116: wifi_6_other31_standard, 117: wifi_6_other32_ssid, 118: wifi_6_other32_bssid, 119: wifi_6_other32_standard, 120: wifi_6_other33_ssid, 121: wifi_6_other33_bssid, 122: wifi_6_other33_standard, 123: wifi_6_other34_ssid, 124: wifi_6_other34_bssid, 125: wifi_6_other34_standard, 126: wifi_6_other35_ssid, 127: wifi_6_other35_bssid, 128: wifi_6_other35_standard, 129: wifi_6_other36_ssid, 130: wifi_6_other36_bssid, 131: wifi_6_other36_standard, 132: wifi_6_other37_ssid, 133: wifi_6_other37_bssid, 134: wifi_6_other37_standard, 135: wifi_6_other38_ssid, 136: wifi_6_other38_bssid, 137: wifi_6_other38_standard, 138: wifi_6_other39_ssid, 139: wifi_6_other39_bssid, 140: wifi_6_other39_standard, 141: wifi_6_other40_ssid, 142: wifi_6_other40_bssid, 143: wifi_6_other40_standard, 144: wifi_6_other41_ssid, 145: wifi_6_other41_bssid, 146: wifi_6_other41_standard, 147: wifi_6_other42_ssid, 148: wifi_6_other42_bssid, 149: wifi_6_other42_standard, 150: wifi_6_other43_ssid, 151: wifi_6_other43_bssid, 152: wifi_6_other43_standard, 153: wifi_6_other44_ssid, 154: wifi_6_other44_bssid, 155: wifi_6_other44_standard, 156: wifi_6_other45_ssid, 157: wifi_6_other45_bssid, 158: wifi_6_other45_standard, 159: wifi_6_other46_ssid, 160: wifi_6_other46_bssid, 161: wifi_6_other46_standard, 162: wifi_6_other47_ssid, 163: wifi_6_other47_bssid, 164: wifi_6_other47_standard, 165: wifi_6_other48_ssid, 166: wifi_6_other48_bssid, 167: wifi_6_other48_standard, 168: wifi_6_other49_ssid, 169: wifi_6_other49_bssid, 170: wifi_6_other49_standard, 171: wifi_6_other50_ssid, 172: wifi_6_other50_bssid, 173: wifi_6_other50_standard, 174: wifi_6_other51_ssid, 175: wifi_6_other51_bssid, 176: wifi_6_other51_standard, 177: wifi_6_other52_ssid, 178: wifi_6_other52_bssid, 179: wifi_6_other52_standard, 180: wifi_6_other53_ssid, 181: wifi_6_other53_bssid, 182: wifi_6_other53_standard, 183: wifi_6_other54_ssid, 184: wifi_6_other54_bssid, 185: wifi_6_other54_standard, 186: wifi_6_other55_ssid, 187: wifi_6_other55_bssid, 188: wifi_6_other55_standard, 189: wifi_6_other56_ssid, 190: wifi_6_other56_bssid, 191: wifi_6_other56_standard, 192: wifi_6_other57_ssid, 193: wifi_6_other57_bssid, 194: wifi_6_other57_standard, 195: wifi_6_other58_ssid, 196: wifi_6_other58_bssid, 197: wifi_6_other58_standard, 198: wifi_6_other59_ssid, 199: wifi_6_other59_bssid, 200: wifi_6_other59_standard, 201: wifi_6_other60_ssid, 202: wifi_6_other60_bssid, 203: wifi_6_other60_standard, 204: wifi_6_other61_ssid, 205: wifi_6_other61_bssid, 206: wifi_6_other61_standard, 207: wifi_6_other62_ssid, 208: wifi_6_other62_bssid, 209: wifi_6_other62_standard, 210: wifi_6_other63_ssid, 211: wifi_6_other63_bssid, 212: wifi_6_other63_standard, 213: wifi_6_other64_ssid, 214: wifi_6_other64_bssid, 215: wifi_6_other64_standard, 216: wifi_6_other65_ssid, 217: wifi_6_other65_bssid, 218: wifi_6_other65_standard, 219: wifi_6_other66_ssid, 220: wifi_6_other66_bssid, 221: wifi_6_other66_standard) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(DATA_DIR / 'game6_sigcap_csv/20251122_sigcap_bowl_general.csv', parse_dates=['timestamp']).assign(Location='Bowl'),
/tmp/ipykernel_29177/35759932.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pd.read_csv(DATA_DIR / 'game6_sigcap_csv/20251122_sigcap_bowl_general.csv', parse_dates=['timestamp']).assign(Location='Bowl'),

/tmp/ipykernel_29177/35759932.py:5: DtypeWarning: Columns (0: override_network_type, 1: cellBandwidths, 2: nr_first_is_primary, 3: nr_first_is_signalStrAPI, 4: nr_other1_is_signalStrAPI, 5: wifi_connected_ssid, 6: wifi_connected_bssid, 7: wifi_connected_standard, 8: wifi_2.4_other3_ssid, 9: wifi_2.4_other3_bssid, 10: wifi_2.4_other3_standard, 11: wifi_2.4_other4_ssid, 12: wifi_2.4_other4_bssid, 13: wifi_2.4_other4_standard, 14: wifi_2.4_other5_ssid, 15: wifi_2.4_other5_bssid, 16: wifi_2.4_other5_standard, 17: wifi_2.4_other6_ssid, 18: wifi_2.4_other6_bssid, 19: wifi_2.4_other6_standard, 20: wifi_2.4_other7_ssid, 21: wifi_2.4_other7_bssid, 22: wifi_2.4_other7_standard, 23: wifi_2.4_other8_ssid, 24: wifi_2.4_other8_bssid, 25: wifi_2.4_other8_standard, 26: wifi_2.4_other9_ssid, 27: wifi_2.4_other9_bssid, 28: wifi_2.4_other9_standard, 29: wifi_2.4_other10_ssid, 30: wifi_2.4_other10_bssid, 31: wifi_2.4_other10_standard, 32: wifi_2.4_other11_ssid, 33: wifi_2.4_other11_bssid, 34: wifi_2.4_other11_standard, 35: wifi_2.4_other12_ssid, 36: wifi_2.4_other12_bssid, 37: wifi_2.4_other12_standard, 38: wifi_2.4_other13_ssid, 39: wifi_2.4_other13_bssid, 40: wifi_2.4_other13_standard, 41: wifi_2.4_other14_ssid, 42: wifi_2.4_other14_bssid, 43: wifi_2.4_other14_standard, 44: wifi_5_other25_ssid, 45: wifi_5_other25_bssid, 46: wifi_5_other25_standard, 47: wifi_5_other26_ssid, 48: wifi_5_other26_bssid, 49: wifi_5_other26_standard, 50: wifi_5_other27_ssid, 51: wifi_5_other27_bssid, 52: wifi_5_other27_standard, 53: wifi_5_other28_ssid, 54: wifi_5_other28_bssid, 55: wifi_5_other28_standard, 56: wifi_5_other29_ssid, 57: wifi_5_other29_bssid, 58: wifi_5_other29_standard, 59: wifi_5_other30_ssid, 60: wifi_5_other30_bssid, 61: wifi_5_other30_standard, 62: wifi_5_other31_ssid, 63: wifi_5_other31_bssid, 64: wifi_5_other31_standard, 65: wifi_5_other32_ssid, 66: wifi_5_other32_bssid, 67: wifi_5_other32_standard, 68: wifi_5_other33_ssid, 69: wifi_5_other33_bssid, 70: wifi_5_other33_standard, 71: wifi_5_other34_ssid, 72: wifi_5_other34_bssid, 73: wifi_5_other34_standard, 74: wifi_5_other35_ssid, 75: wifi_5_other35_bssid, 76: wifi_5_other35_standard, 77: wifi_5_other36_ssid, 78: wifi_5_other36_bssid, 79: wifi_5_other36_standard, 80: wifi_5_other37_ssid, 81: wifi_5_other37_bssid, 82: wifi_5_other37_standard, 83: wifi_5_other38_ssid, 84: wifi_5_other38_bssid, 85: wifi_5_other38_standard, 86: wifi_5_other39_ssid, 87: wifi_5_other39_bssid, 88: wifi_5_other39_standard, 89: wifi_5_other40_ssid, 90: wifi_5_other40_bssid, 91: wifi_5_other40_standard, 92: wifi_5_other41_ssid, 93: wifi_5_other41_bssid, 94: wifi_5_other41_standard, 95: wifi_5_other42_ssid, 96: wifi_5_other42_bssid, 97: wifi_5_other42_standard, 98: wifi_5_other43_ssid, 99: wifi_5_other43_bssid, 100: wifi_5_other43_standard, 101: wifi_5_other44_ssid, 102: wifi_5_other44_bssid, 103: wifi_5_other44_standard, 104: wifi_5_other45_ssid, 105: wifi_5_other45_bssid, 106: wifi_5_other45_standard, 107: wifi_5_other46_ssid, 108: wifi_5_other46_bssid, 109: wifi_5_other46_standard, 110: wifi_5_other47_ssid, 111: wifi_5_other47_bssid, 112: wifi_5_other47_standard, 113: wifi_5_other48_ssid, 114: wifi_5_other48_bssid, 115: wifi_5_other48_standard, 116: wifi_5_other49_ssid, 117: wifi_5_other49_bssid, 118: wifi_5_other49_standard, 119: wifi_5_other50_ssid, 120: wifi_5_other50_bssid, 121: wifi_5_other50_standard, 122: wifi_5_other51_ssid, 123: wifi_5_other51_bssid, 124: wifi_5_other51_standard, 125: wifi_5_other52_ssid, 126: wifi_5_other52_bssid, 127: wifi_5_other52_standard, 128: wifi_5_other53_ssid, 129: wifi_5_other53_bssid, 130: wifi_5_other53_standard, 131: wifi_5_other54_ssid, 132: wifi_5_other54_bssid, 133: wifi_5_other54_standard, 134: wifi_5_other55_ssid, 135: wifi_5_other55_bssid, 136: wifi_5_other55_standard, 137: wifi_5_other56_ssid, 138: wifi_5_other56_bssid, 139: wifi_5_other56_standard, 140: wifi_5_other57_ssid, 141: wifi_5_other57_bssid, 142: wifi_5_other57_standard, 143: wifi_5_other58_ssid, 144: wifi_5_other58_bssid, 145: wifi_5_other58_standard, 146: wifi_5_other59_ssid, 147: wifi_5_other59_bssid, 148: wifi_5_other59_standard, 149: wifi_5_other60_ssid, 150: wifi_5_other60_bssid, 151: wifi_5_other60_standard, 152: wifi_5_other61_ssid, 153: wifi_5_other61_bssid, 154: wifi_5_other61_standard, 155: wifi_5_other62_ssid, 156: wifi_5_other62_bssid, 157: wifi_5_other62_standard, 158: wifi_5_other63_ssid, 159: wifi_5_other63_bssid, 160: wifi_5_other63_standard, 161: wifi_5_other64_ssid, 162: wifi_5_other64_bssid, 163: wifi_5_other64_standard, 164: wifi_5_other65_ssid, 165: wifi_5_other65_bssid, 166: wifi_5_other65_standard, 167: wifi_5_other66_ssid, 168: wifi_5_other66_bssid, 169: wifi_5_other66_standard, 170: wifi_5_other67_ssid, 171: wifi_5_other67_bssid, 172: wifi_5_other67_standard, 173: wifi_5_other68_ssid, 174: wifi_5_other68_bssid, 175: wifi_5_other68_standard, 176: wifi_5_other69_ssid, 177: wifi_5_other69_bssid, 178: wifi_5_other69_standard, 179: wifi_5_other70_ssid, 180: wifi_5_other70_bssid, 181: wifi_5_other70_standard, 182: wifi_5_other71_ssid, 183: wifi_5_other71_bssid, 184: wifi_5_other71_standard, 185: wifi_5_other72_ssid, 186: wifi_5_other72_bssid, 187: wifi_5_other72_standard, 188: wifi_5_other73_ssid, 189: wifi_5_other73_bssid, 190: wifi_5_other73_standard, 191: wifi_5_other74_ssid, 192: wifi_5_other74_bssid, 193: wifi_5_other74_standard, 194: wifi_5_other75_ssid, 195: wifi_5_other75_bssid, 196: wifi_5_other75_standard, 197: wifi_5_other76_ssid, 198: wifi_5_other76_bssid, 199: wifi_5_other76_standard, 200: wifi_5_other77_ssid, 201: wifi_5_other77_bssid, 202: wifi_5_other77_standard, 203: wifi_5_other78_ssid, 204: wifi_5_other78_bssid, 205: wifi_5_other78_standard, 206: wifi_5_other79_ssid, 207: wifi_5_other79_bssid, 208: wifi_5_other79_standard, 209: wifi_5_other80_ssid, 210: wifi_5_other80_bssid, 211: wifi_5_other80_standard, 212: wifi_5_other81_ssid, 213: wifi_5_other81_bssid, 214: wifi_5_other81_standard, 215: wifi_5_other82_ssid, 216: wifi_5_other82_bssid, 217: wifi_5_other82_standard, 218: wifi_5_other83_ssid, 219: wifi_5_other83_bssid, 220: wifi_5_other83_standard, 221: wifi_5_other84_ssid, 222: wifi_5_other84_bssid, 223: wifi_5_other84_standard, 224: wifi_5_other85_ssid, 225: wifi_5_other85_bssid, 226: wifi_5_other85_standard, 227: wifi_5_other86_ssid, 228: wifi_5_other86_bssid, 229: wifi_5_other86_standard, 230: wifi_5_other87_ssid, 231: wifi_5_other87_bssid, 232: wifi_5_other87_standard, 233: wifi_5_other88_ssid, 234: wifi_5_other88_bssid, 235: wifi_5_other88_standard, 236: wifi_5_other89_ssid, 237: wifi_5_other89_bssid, 238: wifi_5_other89_standard, 239: wifi_6_other15_ssid, 240: wifi_6_other15_bssid, 241: wifi_6_other15_standard, 242: wifi_6_other16_ssid, 243: wifi_6_other16_bssid, 244: wifi_6_other16_standard, 245: wifi_6_other17_ssid, 246: wifi_6_other17_bssid, 247: wifi_6_other17_standard, 248: wifi_6_other18_ssid, 249: wifi_6_other18_bssid, 250: wifi_6_other18_standard, 251: wifi_6_other19_ssid, 252: wifi_6_other19_bssid, 253: wifi_6_other19_standard, 254: wifi_6_other20_ssid, 255: wifi_6_other20_bssid, 256: wifi_6_other20_standard, 257: wifi_6_other21_ssid, 258: wifi_6_other21_bssid, 259: wifi_6_other21_standard, 260: wifi_6_other22_ssid, 261: wifi_6_other22_bssid, 262: wifi_6_other22_standard, 263: wifi_6_other23_ssid, 264: wifi_6_other23_bssid, 265: wifi_6_other23_standard, 266: wifi_6_other24_ssid, 267: wifi_6_other24_bssid, 268: wifi_6_other24_standard) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(DATA_DIR / 'game6_sigcap_csv/20251122_sigcap_concourse_general.csv', parse_dates=['timestamp']).assign(Location='Concourse')
/tmp/ipykernel_29177/35759932.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pd.read_csv(DATA_DIR / 'game6_sigcap_csv/20251122_sigcap_concourse_general.csv', parse_dates=['timestamp']).assign(Location='Concourse')

Sigcap data shape: (3770, 8)

          uuid  operator
2328  7c36e7df   Verizon
0     a0654bd3      AT&T
75    64957d65  T-Mobile

,timestamp,latitude,longitude,uuid,operator,Location,network_type*,wifi_connected_primary_freq_mhz
2328,2025-11-22 08:36:58.157000-05:00,41.696351,-86.229814,7c36e7df,Verizon,Concourse,LTE,NaN
2329,2025-11-22 08:37:03.162000-05:00,41.696377,-86.229814,7c36e7df,Verizon,Concourse,LTE,NaN
2330,2025-11-22 08:37:08.158000-05:00,41.696444,-86.229814,7c36e7df,Verizon,Concourse,LTE,NaN
2331,2025-11-22 08:37:13.154000-05:00,41.696508,-86.229812,7c36e7df,Verizon,Concourse,LTE,NaN
2332,2025-11-22 08:37:18.159000-05:00,41.696574,-86.229818,7c36e7df,Verizon,Concourse,LTE,NaN

# ===============================
# ===============================

# C- Browsing analysis

### plc, data creation

In [4]:
df_browser = pd.concat([
    pd.read_csv(DATA_DIR / 'game6_qp_csv/20251122_Game_Bowl_Browser.csv', parse_dates=['Time']).assign(Location='Bowl'),
    pd.read_csv(DATA_DIR / 'game6_qp_csv/20251122_Game_Concourse_Browser.csv', parse_dates=['Time']).assign(Location='Concourse')
]).sort_values('Time')

display(df_browser[['Unit', 'Operator']].value_counts())

# Taken from SigCap
uuid_map = {
    'QualiPoc_619529': '64957d65',	 #T-Mobile
    'QualiPoc_361786': 'a0654bd3',	 #AT&T
    'QualiPoc_396840': '7c36e7df'	 #Verizon
}

df_browser['uuid'] = df_browser['Unit'].map(uuid_map)

print(f"Browser data shape: {df_browser.shape}")
df_browser.head()

Unit             Operator
QualiPoc_619529  T-Mobile    202
QualiPoc_396840  Verizon     161
QualiPoc_361786  AT&T        160
QualiPoc_396840  T-Mobile      5
                 AT&T          4
Name: count, dtype: int64

Browser data shape: (532, 34)

,Time,Latitude,Longitude,Unit,Operator,Technology,Browsing Duration,Download Duration,IP Throughput,Access Duration,...,Host,Protocol,Operation,AP Type,AP Profile Name,Test Name,Direction,Test Status,Location,uuid
0,2025-11-22 16:15:36.749,41.698829,-86.233373,QualiPoc_361786,AT&T,LTE,NaN,NaN,NaN,1208.0,...,instagram.com,HTTP,GET,default supl mms fota,ATT Enhancedphone,Browsing,Downlink,Failed,Bowl,a0654bd3
1,2025-11-22 16:15:49.500,41.698833,-86.233377,QualiPoc_361786,AT&T,LTE,11.574,2.786,5220.086145,608.0,...,tiktok.com,HTTP,GET,default supl mms fota,ATT Enhancedphone,Browsing,Downlink,Completed,Bowl,a0654bd3
2,2025-11-22 16:15:58.940,41.698836,-86.233376,QualiPoc_361786,AT&T,LTE,8.292,4.949,2181.250354,1078.0,...,facebook.com,HTTP,GET,default supl mms fota,ATT Enhancedphone,Browsing,Downlink,Completed,Bowl,a0654bd3
3,2025-11-22 16:17:30.175,41.698837,-86.233385,QualiPoc_361786,AT&T,LTE,NaN,NaN,NaN,884.0,...,ncaa.com,HTTP,GET,default supl mms fota,ATT Enhancedphone,Browsing,Downlink,Failed,Bowl,a0654bd3
0,2025-11-22 16:17:34.131,41.698159,-86.232981,QualiPoc_396840,Verizon,LTE,3.346,0.403,81917.697270,276.0,...,instagram.com,HTTP,GET,default dun supl,Verizon Internet,Browsing,Downlink,Completed,Concourse,7c36e7df

In [5]:
# Correlate df_browser and df_sigcap

# 1. Handle Timezones
# Browser 'Time' is likely naive local time (ET). Localize it.
if df_browser['Time'].dt.tz is None:
    df_browser['Time'] = df_browser['Time'].dt.tz_localize('US/Eastern', ambiguous='infer')

# Sigcap 'timestamp' is already tz-aware. Convert both to UTC for safe merging.
df_browser['Time_utc'] = df_browser['Time'].dt.tz_convert('UTC')
df_sigcap['timestamp_utc'] = df_sigcap['timestamp'].dt.tz_convert('UTC')

# 2. Merge
# We want to bring 'network_type*' and 'wifi_connected_primary_freq_mhz' from sigcap to browser
cols_to_merge = ['timestamp_utc', 'operator', 'network_type*', 'wifi_connected_primary_freq_mhz', 'Location']

cols_to_merge.append('uuid')
df_browser_merged = pd.merge_asof(
    df_browser,
    df_sigcap[cols_to_merge],
    left_on='Time_utc',
    right_on='timestamp_utc',
    by='uuid',
    direction='nearest',
    tolerance=pd.Timedelta('10s')
)

# 3. Cleanup
df_browser_merged = df_browser_merged.drop(columns=['timestamp_utc', 'Time_utc'])

# Rename Location columns for clarity after merge
df_browser_merged = df_browser_merged.rename(columns={'Location_x': 'Location', 'Location_y': 'Location_sigcap'})

conditions = [
    (df_browser_merged['wifi_connected_primary_freq_mhz'].between(5000, 5925, inclusive='both')),
    (df_browser_merged['wifi_connected_primary_freq_mhz'] > 5925),
    (df_browser_merged['wifi_connected_primary_freq_mhz'] < 5000)
]
choices = ['Wi-Fi 5', 'Wi-Fi 6', 'Wi-Fi 2.4']
df_browser_merged['operator'] = np.select(conditions, choices, default=df_browser_merged['operator'])

# Check for Location mismatches
df_mismatched_Locations = df_browser_merged[df_browser_merged['Location'] != df_browser_merged['Location_sigcap']]
print(f"Rows with mismatched Locations: {df_mismatched_Locations.shape[0]}")
display(df_mismatched_Locations)

# Remove rows with mismatched Location
df_browser_merged = df_browser_merged[df_browser_merged['Location'] == df_browser_merged['Location_sigcap']]

# Display result
print(f"Merged shape: {df_browser_merged.shape}")
display(df_browser_merged)
df_browser_merged.to_csv(OUTPUT_DIR / 'df_browser_merged_gd6.csv', index=False)

Rows with mismatched Locations: 10

,Time,Latitude,Longitude,Unit,Operator,Technology,Browsing Duration,Download Duration,IP Throughput,Access Duration,...,AP Profile Name,Test Name,Direction,Test Status,Location,uuid,operator,network_type*,wifi_connected_primary_freq_mhz,Location_sigcap
512,2025-11-22 18:54:49.158000-05:00,41.697616,-86.234641,QualiPoc_619529,T-Mobile,5G NR,1.925,0.167,239037.508982,211.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
513,2025-11-22 18:54:56.720000-05:00,41.697634,-86.234650,QualiPoc_619529,T-Mobile,5G NR,6.296,2.198,8628.236579,393.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
514,2025-11-22 18:55:00.613000-05:00,41.697645,-86.234669,QualiPoc_619529,T-Mobile,5G NR,2.590,2.073,4192.968644,282.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
515,2025-11-22 18:55:06.555000-05:00,41.697649,-86.234672,QualiPoc_619529,T-Mobile,5G NR,4.649,0.452,103167.557522,310.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
516,2025-11-22 18:55:13.815000-05:00,41.697651,-86.234676,QualiPoc_619529,T-Mobile,5G NR,5.956,0.561,58311.001783,886.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
517,2025-11-22 18:56:28.744000-05:00,41.697632,-86.234703,QualiPoc_619529,T-Mobile,5G NR,1.164,0.073,670375.671233,96.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
518,2025-11-22 18:56:32.206000-05:00,41.697632,-86.234703,QualiPoc_619529,T-Mobile,5G NR,2.169,0.342,73086.315789,315.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
519,2025-11-22 18:56:35.001000-05:00,41.697632,-86.234703,QualiPoc_619529,T-Mobile,5G NR,1.531,1.118,7975.327370,177.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
520,2025-11-22 18:56:38.659000-05:00,41.697632,-86.234703,QualiPoc_619529,T-Mobile,5G NR,2.465,0.289,159581.979239,114.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
521,2025-11-22 18:56:43.563000-05:00,41.697631,-86.234703,QualiPoc_619529,T-Mobile,5G NR,3.661,0.786,41300.926209,100.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN

Merged shape: (522, 38)

,Time,Latitude,Longitude,Unit,Operator,Technology,Browsing Duration,Download Duration,IP Throughput,Access Duration,...,AP Profile Name,Test Name,Direction,Test Status,Location,uuid,operator,network_type*,wifi_connected_primary_freq_mhz,Location_sigcap
0,2025-11-22 16:15:36.749000-05:00,41.698829,-86.233373,QualiPoc_361786,AT&T,LTE,NaN,NaN,NaN,1208.0,...,ATT Enhancedphone,Browsing,Downlink,Failed,Bowl,a0654bd3,AT&T,NR-NSA,NaN,Bowl
1,2025-11-22 16:15:49.500000-05:00,41.698833,-86.233377,QualiPoc_361786,AT&T,LTE,11.574,2.786,5220.086145,608.0,...,ATT Enhancedphone,Browsing,Downlink,Completed,Bowl,a0654bd3,AT&T,LTE,NaN,Bowl
2,2025-11-22 16:15:58.940000-05:00,41.698836,-86.233376,QualiPoc_361786,AT&T,LTE,8.292,4.949,2181.250354,1078.0,...,ATT Enhancedphone,Browsing,Downlink,Completed,Bowl,a0654bd3,AT&T,LTE,NaN,Bowl
3,2025-11-22 16:17:30.175000-05:00,41.698837,-86.233385,QualiPoc_361786,AT&T,LTE,NaN,NaN,NaN,884.0,...,ATT Enhancedphone,Browsing,Downlink,Failed,Bowl,a0654bd3,AT&T,LTE,NaN,Bowl
4,2025-11-22 16:17:34.131000-05:00,41.698159,-86.232981,QualiPoc_396840,Verizon,LTE,3.346,0.403,81917.697270,276.0,...,Verizon Internet,Browsing,Downlink,Completed,Concourse,7c36e7df,Verizon,LTE,NaN,Concourse
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,2025-11-22 18:59:28.590000-05:00,41.697631,-86.234618,QualiPoc_619529,T-Mobile,5G NR,1.780,0.164,213100.682927,219.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse
528,2025-11-22 18:59:36.023000-05:00,41.697630,-86.234617,QualiPoc_619529,T-Mobile,5G NR,6.257,2.319,7850.031910,402.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse
529,2025-11-22 18:59:39.461000-05:00,41.697628,-86.234617,QualiPoc_619529,T-Mobile,5G NR,2.141,1.773,4996.227862,85.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse
530,2025-11-22 18:59:44.144000-05:00,41.697618,-86.234593,QualiPoc_619529,T-Mobile,5G NR,3.417,0.253,185059.383399,310.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse
531,2025-11-22 18:59:51.673000-05:00,41.697611,-86.234607,QualiPoc_619529,T-Mobile,5G NR,6.234,0.606,54001.320132,893.0,...,T-Mobile US LTE,Browsing,Downlink,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse

# ===============================
# ===============================

# D-Posting tests

## Instagram

### plc, Instagram data creation

In [6]:
df_instagram = pd.concat([
    pd.read_csv(DATA_DIR / 'game6_qp_csv/20251122_Game_Bowl_Data_Applications.csv', parse_dates=['Time']).assign(Location='Bowl'),
    pd.read_csv(DATA_DIR / 'game6_qp_csv/20251122_Game_Concourse_Data_Applications.csv', parse_dates=['Time']).assign(Location='Concourse')
]).sort_values('Time')

df_instagram = df_instagram[df_instagram['Test Name'] == 'Instagram']

display(df_instagram[['Unit', 'Operator']].value_counts())

# Taken from SigCap
uuid_map = {
    'QualiPoc_619529': '64957d65',	 #T-Mobile
    'QualiPoc_361786': 'a0654bd3',	 #AT&T
    'QualiPoc_396840': '7c36e7df'	 #Verizon
}

df_instagram['uuid'] = df_instagram['Unit'].map(uuid_map)

print(f"Data_Applications data shape: {df_instagram.shape}")
df_instagram.head()

Unit             Operator
QualiPoc_619529  T-Mobile    42
QualiPoc_361786  AT&T        32
QualiPoc_396840  Verizon     32
                 T-Mobile     1
                 AT&T         1
Name: count, dtype: int64

Data_Applications data shape: (108, 26)

,Time,Latitude,Longitude,Unit,Operator,Technology,Service,Action,Direction,Host,...,Max IP Throughput DL,IP Throughput UL,Max IP Throughput UL,Bytes Transferred DL,Bytes Transferred UL,Test Name,Direction.1,Test Status,Location,uuid
5,2025-11-22 16:18:11.660,41.698832,-86.233387,QualiPoc_361786,AT&T,LTE,Instagram,Post Picture,SEND,NaN,...,NaN,NaN,NaN,NaN,999378.0,Instagram,Send,System Release,Bowl,a0654bd3
5,2025-11-22 16:18:29.479,41.698189,-86.232993,QualiPoc_396840,Verizon,LTE,Instagram,Post Picture,SEND,NaN,...,11955.048,383.016,1300.840,NaN,999114.0,Instagram,Send,Completed,Concourse,7c36e7df
11,2025-11-22 16:20:20.025,41.698187,-86.232979,QualiPoc_396840,Verizon,LTE,Instagram,Post Picture,SEND,NaN,...,53131.112,936.392,8151.224,NaN,999054.0,Instagram,Send,Completed,Concourse,7c36e7df
11,2025-11-22 16:20:33.093,41.698831,-86.233381,QualiPoc_361786,AT&T,LTE,Instagram,Post Picture,SEND,NaN,...,0.000,0.000,0.000,NaN,999045.0,Instagram,Send,Completed,Bowl,a0654bd3
17,2025-11-22 16:22:11.815,41.697958,-86.234545,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,39785.208,1038.904,3533.376,NaN,999360.0,Instagram,Send,Completed,Bowl,64957d65

In [7]:
# Correlate df_instagram and df_sigcap

# 1. Handle Timezones
# Browser 'Time' is likely naive local time (ET). Localize it.
if df_instagram['Time'].dt.tz is None:
    df_instagram['Time'] = df_instagram['Time'].dt.tz_localize('US/Eastern', ambiguous='infer')

# Sigcap 'timestamp' is already tz-aware. Convert both to UTC for safe merging.
df_instagram['Time_utc'] = df_instagram['Time'].dt.tz_convert('UTC')
df_sigcap['timestamp_utc'] = df_sigcap['timestamp'].dt.tz_convert('UTC')

# 2. Merge
# We want to bring 'network_type*' and 'wifi_connected_primary_freq_mhz' from sigcap to browser
cols_to_merge = ['timestamp_utc', 'operator', 'network_type*', 'wifi_connected_primary_freq_mhz', 'Location']

cols_to_merge.append('uuid')
df_instagram_merged = pd.merge_asof(
    df_instagram,
    df_sigcap[cols_to_merge],
    left_on='Time_utc',
    right_on='timestamp_utc',
    by='uuid',
    direction='nearest',
    tolerance=pd.Timedelta('10s')
)

# 3. Cleanup
df_instagram_merged = df_instagram_merged.drop(columns=['timestamp_utc', 'Time_utc'])

# Rename Location columns for clarity after merge
df_instagram_merged = df_instagram_merged.rename(columns={'Location_x': 'Location', 'Location_y': 'Location_sigcap'})

conditions = [
    (df_instagram_merged['wifi_connected_primary_freq_mhz'].between(5000, 5925, inclusive='both')),
    (df_instagram_merged['wifi_connected_primary_freq_mhz'] > 5925),
    (df_instagram_merged['wifi_connected_primary_freq_mhz'] < 5000)
]
choices = ['Wi-Fi 5', 'Wi-Fi 6', 'Wi-Fi 2.4']
df_instagram_merged['operator'] = np.select(conditions, choices, default=df_instagram_merged['operator'])

# Check for Location mismatches
df_mismatched_Locations = df_instagram_merged[df_instagram_merged['Location'] != df_instagram_merged['Location_sigcap']]
print(f"Rows with mismatched Locations: {df_mismatched_Locations.shape[0]}")
display(df_mismatched_Locations)

# Remove rows with mismatched Location
df_instagram_merged = df_instagram_merged[df_instagram_merged['Location'] == df_instagram_merged['Location_sigcap']]

# Display result
print(f"Merged shape: {df_instagram_merged.shape}")
display(df_instagram_merged)
df_instagram_merged.to_csv(OUTPUT_DIR / 'df_instagram_merged_gd6.csv', index=False)

Rows with mismatched Locations: 2

,Time,Latitude,Longitude,Unit,Operator,Technology,Service,Action,Direction,Host,...,Bytes Transferred UL,Test Name,Direction.1,Test Status,Location,uuid,operator,network_type*,wifi_connected_primary_freq_mhz,Location_sigcap
104,2025-11-22 18:55:24.556000-05:00,41.697654,-86.234673,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,999225.0,Instagram,Send,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
105,2025-11-22 18:56:54.248000-05:00,41.697631,-86.234703,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,998962.0,Instagram,Send,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN

Merged shape: (106, 30)

,Time,Latitude,Longitude,Unit,Operator,Technology,Service,Action,Direction,Host,...,Bytes Transferred UL,Test Name,Direction.1,Test Status,Location,uuid,operator,network_type*,wifi_connected_primary_freq_mhz,Location_sigcap
0,2025-11-22 16:18:11.660000-05:00,41.698832,-86.233387,QualiPoc_361786,AT&T,LTE,Instagram,Post Picture,SEND,NaN,...,999378.0,Instagram,Send,System Release,Bowl,a0654bd3,AT&T,LTE,NaN,Bowl
1,2025-11-22 16:18:29.479000-05:00,41.698189,-86.232993,QualiPoc_396840,Verizon,LTE,Instagram,Post Picture,SEND,NaN,...,999114.0,Instagram,Send,Completed,Concourse,7c36e7df,Verizon,LTE,NaN,Concourse
2,2025-11-22 16:20:20.025000-05:00,41.698187,-86.232979,QualiPoc_396840,Verizon,LTE,Instagram,Post Picture,SEND,NaN,...,999054.0,Instagram,Send,Completed,Concourse,7c36e7df,Wi-Fi 6,LTE,6295.0,Concourse
3,2025-11-22 16:20:33.093000-05:00,41.698831,-86.233381,QualiPoc_361786,AT&T,LTE,Instagram,Post Picture,SEND,NaN,...,999045.0,Instagram,Send,Completed,Bowl,a0654bd3,AT&T,LTE,NaN,Bowl
4,2025-11-22 16:22:11.815000-05:00,41.697958,-86.234545,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,999360.0,Instagram,Send,Completed,Bowl,64957d65,T-Mobile,NR,NaN,Bowl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2025-11-22 18:48:58.103000-05:00,41.697511,-86.233300,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,999211.0,Instagram,Send,Completed,Concourse,64957d65,Wi-Fi 6,NR,6055.0,Concourse
102,2025-11-22 18:51:27.907000-05:00,41.697463,-86.234229,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,999000.0,Instagram,Send,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse
103,2025-11-22 18:53:21.237000-05:00,41.697498,-86.234198,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,998993.0,Instagram,Send,Completed,Concourse,64957d65,Wi-Fi 6,NR,6695.0,Concourse
106,2025-11-22 18:58:41.654000-05:00,41.697639,-86.234661,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,998938.0,Instagram,Send,Failed,Concourse,64957d65,Wi-Fi 5,NR,5260.0,Concourse
107,2025-11-22 19:00:03.662000-05:00,41.697606,-86.234603,QualiPoc_619529,T-Mobile,5G NR,Instagram,Post Picture,SEND,NaN,...,998995.0,Instagram,Send,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse

## Whatsapp

### plc, whatsapp data creation

In [8]:
df_whatsapp = pd.concat([
    pd.read_csv(DATA_DIR / 'game6_qp_csv/20251122_Game_Bowl_Messaging.csv', parse_dates=['Time']).assign(Location='Bowl'),
    pd.read_csv(DATA_DIR / 'game6_qp_csv/20251122_Game_Concourse_Messaging.csv', parse_dates=['Time']).assign(Location='Concourse')
]).sort_values('Time')

display(df_whatsapp[['Unit', 'Operator']].value_counts())

# Taken from SigCap
uuid_map = {
    'QualiPoc_619529': '64957d65',	 #T-Mobile
    'QualiPoc_361786': 'a0654bd3',	 #AT&T
    'QualiPoc_396840': '7c36e7df'	 #Verizon
}

df_whatsapp['uuid'] = df_whatsapp['Unit'].map(uuid_map)

print(f"Messaging data shape: {df_whatsapp.shape}")
df_whatsapp.head()

Unit             Operator
QualiPoc_619529  T-Mobile    80
QualiPoc_361786  AT&T        64
QualiPoc_396840  Verizon     63
                 T-Mobile     2
                 AT&T         1
Name: count, dtype: int64

Messaging data shape: (210, 19)

,Time,Latitude,Longitude,Unit,Operator,Technology,Send Duration,Delivery Duration,Start Time,Receive Time,Transmission Status,Delivery Status,Delivery Notification,Action Type,File Size,Job Name,Test Status,Location,uuid
0,2025-11-22 16:18:18.399,41.698826,-86.233389,QualiPoc_361786,AT&T,LTE,3.586,3.593,2025-11-22 16:18:14.081,NaN,Successful,Successful,Enabled,Send Text,NaN,WhatsApp Send,Completed,Bowl,a0654bd3
0,2025-11-22 16:18:32.266,41.698189,-86.232993,QualiPoc_396840,Verizon,LTE,0.330,0.404,2025-11-22 16:18:31.150,NaN,Successful,Successful,Enabled,Send Text,NaN,WhatsApp Send,Completed,Concourse,7c36e7df
1,2025-11-22 16:18:43.623,41.698838,-86.233377,QualiPoc_361786,AT&T,LTE,16.908,16.915,2025-11-22 16:18:25.826,NaN,Successful,Successful,Enabled,Send Picture,999045.0,WhatsApp Send,Completed,Bowl,a0654bd3
1,2025-11-22 16:18:44.897,41.698176,-86.232986,QualiPoc_396840,Verizon,LTE,4.258,4.396,2025-11-22 16:18:39.578,NaN,Successful,Successful,Enabled,Send Picture,999054.0,WhatsApp Send,Completed,Concourse,7c36e7df
2,2025-11-22 16:20:22.893,41.698212,-86.232989,QualiPoc_396840,Verizon,LTE,0.550,0.556,2025-11-22 16:20:21.609,NaN,Successful,Successful,Enabled,Send Text,NaN,WhatsApp Send,Completed,Concourse,7c36e7df

In [9]:
# Correlate df_whatsapp and df_sigcap

# 1. Handle Timezones
# Browser 'Time' is likely naive local time (ET). Localize it.
if df_whatsapp['Time'].dt.tz is None:
    df_whatsapp['Time'] = df_whatsapp['Time'].dt.tz_localize('US/Eastern', ambiguous='infer')

# Sigcap 'timestamp' is already tz-aware. Convert both to UTC for safe merging.
df_whatsapp['Time_utc'] = df_whatsapp['Time'].dt.tz_convert('UTC')
df_sigcap['timestamp_utc'] = df_sigcap['timestamp'].dt.tz_convert('UTC')

# 2. Merge
# We want to bring 'network_type*' and 'wifi_connected_primary_freq_mhz' from sigcap to browser
cols_to_merge = ['timestamp_utc', 'operator', 'network_type*', 'wifi_connected_primary_freq_mhz', 'Location']

cols_to_merge.append('uuid')
df_whatsapp_merged = pd.merge_asof(
    df_whatsapp,
    df_sigcap[cols_to_merge],
    left_on='Time_utc',
    right_on='timestamp_utc',
    by='uuid',
    direction='nearest',
    tolerance=pd.Timedelta('10s')
)

# 3. Cleanup
df_whatsapp_merged = df_whatsapp_merged.drop(columns=['timestamp_utc', 'Time_utc'])

# Rename Location columns for clarity after merge
df_whatsapp_merged = df_whatsapp_merged.rename(columns={'Location_x': 'Location', 'Location_y': 'Location_sigcap'})

conditions = [
    (df_whatsapp_merged['wifi_connected_primary_freq_mhz'].between(5000, 5925, inclusive='both')),
    (df_whatsapp_merged['wifi_connected_primary_freq_mhz'] > 5925),
    (df_whatsapp_merged['wifi_connected_primary_freq_mhz'] < 5000)
]
choices = ['Wi-Fi 5', 'Wi-Fi 6', 'Wi-Fi 2.4']
df_whatsapp_merged['operator'] = np.select(conditions, choices, default=df_whatsapp_merged['operator'])

# Check for Location mismatches
df_mismatched_Locations = df_whatsapp_merged[df_whatsapp_merged['Location'] != df_whatsapp_merged['Location_sigcap']]
print(f"Rows with mismatched Locations: {df_mismatched_Locations.shape[0]}")
display(df_mismatched_Locations)

# Remove rows with mismatched Location
df_whatsapp_merged = df_whatsapp_merged[df_whatsapp_merged['Location'] == df_whatsapp_merged['Location_sigcap']]



# 1. Define the condition for the mismatch
condition = (df_whatsapp_merged['Operator'] == 'T-Mobile') & (df_whatsapp_merged['operator'] == 'Verizon')

# 2. Update the lowercase column with the uppercase column's value
df_whatsapp_merged.loc[condition, 'operator'] = df_whatsapp_merged.loc[condition, 'Operator']



# Display result
print(f"Merged shape: {df_whatsapp_merged.shape}")
display(df_whatsapp_merged)
df_whatsapp_merged.to_csv(OUTPUT_DIR / 'df_whatsapp_merged_gd6.csv', index=False)

Rows with mismatched Locations: 4

,Time,Latitude,Longitude,Unit,Operator,Technology,Send Duration,Delivery Duration,Start Time,Receive Time,...,Action Type,File Size,Job Name,Test Status,Location,uuid,operator,network_type*,wifi_connected_primary_freq_mhz,Location_sigcap
202,2025-11-22 18:55:26.604000-05:00,41.697654,-86.234674,QualiPoc_619529,T-Mobile,5G NR,0.302,0.418,2025-11-22 18:55:25.881,NaN,...,Send Text,NaN,WhatsApp Send,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
203,2025-11-22 18:55:34.564000-05:00,41.697651,-86.234647,QualiPoc_619529,T-Mobile,5G NR,0.953,1.172,2025-11-22 18:55:33.116,NaN,...,Send Picture,998962.0,WhatsApp Send,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
204,2025-11-22 18:56:56.377000-05:00,41.697633,-86.234701,QualiPoc_619529,T-Mobile,5G NR,0.255,0.474,2025-11-22 18:56:55.600,NaN,...,Send Text,NaN,WhatsApp Send,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN
205,2025-11-22 18:57:04.826000-05:00,41.697635,-86.234708,QualiPoc_619529,T-Mobile,5G NR,1.402,1.504,2025-11-22 18:57:02.953,NaN,...,Send Picture,998938.0,WhatsApp Send,Completed,Concourse,64957d65,NaN,NaN,NaN,NaN

Merged shape: (206, 23)

,Time,Latitude,Longitude,Unit,Operator,Technology,Send Duration,Delivery Duration,Start Time,Receive Time,...,Action Type,File Size,Job Name,Test Status,Location,uuid,operator,network_type*,wifi_connected_primary_freq_mhz,Location_sigcap
0,2025-11-22 16:18:18.399000-05:00,41.698826,-86.233389,QualiPoc_361786,AT&T,LTE,3.586,3.593,2025-11-22 16:18:14.081,NaN,...,Send Text,NaN,WhatsApp Send,Completed,Bowl,a0654bd3,AT&T,LTE,NaN,Bowl
1,2025-11-22 16:18:32.266000-05:00,41.698189,-86.232993,QualiPoc_396840,Verizon,LTE,0.330,0.404,2025-11-22 16:18:31.150,NaN,...,Send Text,NaN,WhatsApp Send,Completed,Concourse,7c36e7df,Verizon,LTE,NaN,Concourse
2,2025-11-22 16:18:43.623000-05:00,41.698838,-86.233377,QualiPoc_361786,AT&T,LTE,16.908,16.915,2025-11-22 16:18:25.826,NaN,...,Send Picture,999045.0,WhatsApp Send,Completed,Bowl,a0654bd3,AT&T,LTE,NaN,Bowl
3,2025-11-22 16:18:44.897000-05:00,41.698176,-86.232986,QualiPoc_396840,Verizon,LTE,4.258,4.396,2025-11-22 16:18:39.578,NaN,...,Send Picture,999054.0,WhatsApp Send,Completed,Concourse,7c36e7df,Verizon,LTE,NaN,Concourse
4,2025-11-22 16:20:22.893000-05:00,41.698212,-86.232989,QualiPoc_396840,Verizon,LTE,0.550,0.556,2025-11-22 16:20:21.609,NaN,...,Send Text,NaN,WhatsApp Send,Completed,Concourse,7c36e7df,Wi-Fi 6,LTE,6295.0,Concourse
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,2025-11-22 18:53:32.064000-05:00,41.697520,-86.234216,QualiPoc_619529,T-Mobile,5G NR,1.528,1.698,2025-11-22 18:53:30.019,NaN,...,Send Picture,999225.0,WhatsApp Send,Completed,Concourse,64957d65,Wi-Fi 6,NR,6695.0,Concourse
206,2025-11-22 18:58:43.541000-05:00,41.697648,-86.234658,QualiPoc_619529,T-Mobile,5G NR,0.276,0.337,2025-11-22 18:58:42.923,NaN,...,Send Text,NaN,WhatsApp Send,Completed,Concourse,64957d65,Wi-Fi 5,NR,5260.0,Concourse
207,2025-11-22 18:58:51.479000-05:00,41.697645,-86.234639,QualiPoc_619529,T-Mobile,5G NR,0.949,1.067,2025-11-22 18:58:50.137,NaN,...,Send Picture,998995.0,WhatsApp Send,Completed,Concourse,64957d65,Wi-Fi 5,NR,5260.0,Concourse
208,2025-11-22 19:00:05.764000-05:00,41.697606,-86.234603,QualiPoc_619529,T-Mobile,5G NR,0.313,0.526,2025-11-22 19:00:04.913,NaN,...,Send Text,NaN,WhatsApp Send,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse
209,2025-11-22 19:00:14.252000-05:00,41.697607,-86.234600,QualiPoc_619529,T-Mobile,5G NR,1.146,1.409,2025-11-22 19:00:12.541,NaN,...,Send Picture,999189.0,WhatsApp Send,Completed,Concourse,64957d65,T-Mobile,NR,NaN,Concourse